[build]
  command = "npm install && npx prisma generate && npx prisma db push && node prisma/seed.mjs && npm run build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_FB_PIXEL_ID" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
