import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const WILAYAS = [
  { id: 1, name: 'Adrar', price: 800, priceOffice: 600 },{ id: 2, name: 'Chlef', price: 500, priceOffice: 400 },
  { id: 3, name: 'Laghouat', price: 700, priceOffice: 500 },{ id: 4, name: 'Oum El Bouaghi', price: 500, priceOffice: 400 },
  { id: 5, name: 'Batna', price: 500, priceOffice: 400 },{ id: 6, name: 'Béjaïa', price: 400, priceOffice: 300 },
  { id: 7, name: 'Biskra', price: 700, priceOffice: 500 },{ id: 8, name: 'Béchar', price: 900, priceOffice: 700 },
  { id: 9, name: 'Blida', price: 300, priceOffice: 200 },{ id: 10, name: 'Bouira', price: 400, priceOffice: 300 },
  { id: 11, name: 'Tamanrasset', price: 1200, priceOffice: 900 },{ id: 12, name: 'Tébessa', price: 600, priceOffice: 500 },
  { id: 13, name: 'Tlemcen', price: 600, priceOffice: 500 },{ id: 14, name: 'Tiaret', price: 600, priceOffice: 500 },
  { id: 15, name: 'Tizi Ouzou', price: 400, priceOffice: 300 },{ id: 16, name: 'Alger', price: 300, priceOffice: 200 },
  { id: 17, name: 'Djelfa', price: 600, priceOffice: 500 },{ id: 18, name: 'Jijel', price: 500, priceOffice: 400 },
  { id: 19, name: 'Sétif', price: 400, priceOffice: 300 },{ id: 20, name: 'Saïda', price: 600, priceOffice: 500 },
  { id: 21, name: 'Skikda', price: 500, priceOffice: 400 },{ id: 22, name: 'Sidi Bel Abbès', price: 600, priceOffice: 500 },
  { id: 23, name: 'Annaba', price: 500, priceOffice: 400 },{ id: 24, name: 'Guelma', price: 500, priceOffice: 400 },
  { id: 25, name: 'Constantine', price: 500, priceOffice: 400 },{ id: 26, name: 'Médéa', price: 400, priceOffice: 300 },
  { id: 27, name: 'Mostaganem', price: 500, priceOffice: 400 },{ id: 28, name: 'Msila', price: 600, priceOffice: 500 },
  { id: 29, name: 'Mascara', price: 600, priceOffice: 500 },{ id: 30, name: 'Ouargla', price: 800, priceOffice: 600 },
  { id: 31, name: 'Oran', price: 500, priceOffice: 400 },{ id: 32, name: 'El Bayadh', price: 800, priceOffice: 600 },
  { id: 33, name: 'Illizi', price: 1200, priceOffice: 900 },{ id: 34, name: 'Bordj Bou Arreridj', price: 500, priceOffice: 400 },
  { id: 35, name: 'Boumerdès', price: 300, priceOffice: 200 },{ id: 36, name: 'El Tarf', price: 600, priceOffice: 500 },
  { id: 37, name: 'Tindouf', price: 1200, priceOffice: 900 },{ id: 38, name: 'Tissemsilt', price: 500, priceOffice: 400 },
  { id: 39, name: 'El Oued', price: 700, priceOffice: 500 },{ id: 40, name: 'Khenchela', price: 600, priceOffice: 500 },
  { id: 41, name: 'Souk Ahras', price: 600, priceOffice: 500 },{ id: 42, name: 'Tipaza', price: 300, priceOffice: 200 },
  { id: 43, name: 'Mila', price: 500, priceOffice: 400 },{ id: 44, name: 'Aïn Defla', price: 400, priceOffice: 300 },
  { id: 45, name: 'Naâma', price: 700, priceOffice: 500 },{ id: 46, name: 'Aïn Témouchent', price: 500, priceOffice: 400 },
  { id: 47, name: 'Ghardaïa', price: 700, priceOffice: 500 },{ id: 48, name: 'Relizane', price: 500, priceOffice: 400 },
  { id: 49, name: 'Timimoun', price: 1000, priceOffice: 800 },{ id: 50, name: 'Bordj Badji Mokhtar', price: 1400, priceOffice: 1100 },
  { id: 51, name: 'Ouled Djellal', price: 800, priceOffice: 600 },{ id: 52, name: 'Béni Abbès', price: 1000, priceOffice: 800 },
  { id: 53, name: 'In Salah', price: 1300, priceOffice: 1000 },{ id: 54, name: 'In Guezzam', price: 1500, priceOffice: 1200 },
  { id: 55, name: 'Touggourt', price: 800, priceOffice: 600 },{ id: 56, name: 'Djanet', price: 1400, priceOffice: 1100 },
  { id: 57, name: "El M'Ghair", price: 700, priceOffice: 500 },{ id: 58, name: 'El Meniaa', price: 900, priceOffice: 700 },
];

// All communes for each wilaya
const COMMUNES = [
  { name: 'Adrar', wilayaId: 1 },{ name: 'Tamest', wilayaId: 1 },{ name: 'Reggane', wilayaId: 1 },
  { name: 'In Zghmir', wilayaId: 1 },{ name: 'Tit', wilayaId: 1 },{ name: 'Tsabit', wilayaId: 1 },
  { name: 'Zaouiet Kounta', wilayaId: 1 },{ name: 'Aoulef', wilayaId: 1 },{ name: 'Tamekten', wilayaId: 1 },
  { name: 'Tamantit', wilayaId: 1 },{ name: 'Fenoughil', wilayaId: 1 },{ name: 'Sali', wilayaId: 1 },
  { name: 'Akabli', wilayaId: 1 },{ name: 'Ouled Ahmed Tammi', wilayaId: 1 },{ name: 'Bouda', wilayaId: 1 },
  { name: 'Sebaa', wilayaId: 1 },{ name: 'Chlef', wilayaId: 2 },{ name: 'Ténès', wilayaId: 2 },
  { name: 'Bénairia', wilayaId: 2 },{ name: 'Bouzegha', wilayaId: 2 },{ name: 'Chettia', wilayaId: 2 },
  { name: 'Dahra', wilayaId: 2 },{ name: 'El Hadjeb', wilayaId: 2 },{ name: 'El Karimia', wilayaId: 2 },
  { name: 'Harchoun', wilayaId: 2 },{ name: 'Herenfa', wilayaId: 2 },{ name: 'Labiod Medjadja', wilayaId: 2 },
  { name: 'Moussadek', wilayaId: 2 },{ name: 'Oued Fodda', wilayaId: 2 },{ name: 'Ouled Abbes', wilayaId: 2 },
  { name: 'Ouled Ben Abdelkader', wilayaId: 2 },{ name: 'Ouled Fares', wilayaId: 2 },
  { name: 'Oum Drou', wilayaId: 2 },{ name: 'Sendjas', wilayaId: 2 },{ name: 'Sidi Abderrahmane', wilayaId: 2 },
  { name: 'Sidi Akkacha', wilayaId: 2 },{ name: 'Sobha', wilayaId: 2 },{ name: 'Tadjena', wilayaId: 2 },
  { name: 'Talghemt', wilayaId: 2 },{ name: 'Taougrit', wilayaId: 2 },{ name: 'Zeboudja', wilayaId: 2 },
  { name: 'Ain Merane', wilayaId: 2 },{ name: 'Breira', wilayaId: 2 },{ name: 'Beni Rached', wilayaId: 2 },
  { name: 'Abou El Hassan', wilayaId: 2 },{ name: 'El Marsa', wilayaId: 2 },{ name: 'Boukadir', wilayaId: 2 },
  { name: 'Laghouat', wilayaId: 3 },{ name: 'Aflou', wilayaId: 3 },{ name: 'Ksar El Hirane', wilayaId: 3 },
  { name: 'Mekhareg', wilayaId: 3 },{ name: 'Sidi Makhlouf', wilayaId: 3 },{ name: 'Hassi Delaa', wilayaId: 3 },
  { name: 'El Ghicha', wilayaId: 3 },{ name: 'Oued Morra', wilayaId: 3 },{ name: 'Tadjemout', wilayaId: 3 },
  { name: 'Tadjrouna', wilayaId: 3 },{ name: 'Ain Sidi Ali', wilayaId: 3 },{ name: 'Brida', wilayaId: 3 },
  { name: 'El Assafia', wilayaId: 3 },{ name: 'Sidi Bouzid', wilayaId: 3 },{ name: "Oued M'Zi", wilayaId: 3 },
  { name: 'Kheneg', wilayaId: 3 },{ name: 'Sebgag', wilayaId: 3 },{ name: 'El Houaita', wilayaId: 3 },
  { name: 'Benacer Benchohra', wilayaId: 3 },{ name: 'Sidi Ali', wilayaId: 3 },
  { name: 'Ain Madhi', wilayaId: 3 },{ name: 'Gueltat Sidi Saad', wilayaId: 3 },
  { name: 'Touila', wilayaId: 3 },{ name: 'Beidha', wilayaId: 3 },{ name: 'Oum El Bouaghi', wilayaId: 4 },
  { name: 'Ain Babouche', wilayaId: 4 },{ name: 'Ain Beida', wilayaId: 4 },{ name: 'Ain Diss', wilayaId: 4 },
  { name: 'Ain Fakroun', wilayaId: 4 },{ name: 'Ain Kercha', wilayaId: 4 },{ name: "Ain M'lila", wilayaId: 4 },
  { name: 'Ain Zitoun', wilayaId: 4 },{ name: 'Berriche', wilayaId: 4 },{ name: 'Bir Chouhada', wilayaId: 4 },
  { name: 'Dhalaa', wilayaId: 4 },{ name: 'El Amiria', wilayaId: 4 },{ name: 'El Belala', wilayaId: 4 },
  { name: 'El Djazia', wilayaId: 4 },{ name: 'Fkirina', wilayaId: 4 },{ name: 'Hanchir Toumghani', wilayaId: 4 },
  { name: 'Ksar Sbahi', wilayaId: 4 },{ name: 'Meskiana', wilayaId: 4 },{ name: 'Oued Nini', wilayaId: 4 },
  { name: 'Ouled Gacem', wilayaId: 4 },{ name: 'Ouled Hamla', wilayaId: 4 },
  { name: 'Ouled Zouai', wilayaId: 4 },{ name: 'Rahia', wilayaId: 4 },{ name: 'Sigus', wilayaId: 4 },
  { name: 'Souk Naamane', wilayaId: 4 },{ name: 'Zorg', wilayaId: 4 },{ name: 'Behir Chergui', wilayaId: 4 },
  { name: 'El Harmilia', wilayaId: 4 },{ name: 'Ain El Bey', wilayaId: 4 },{ name: 'Batna', wilayaId: 5 },
  { name: 'Ain Touta', wilayaId: 5 },{ name: 'Ain Yagout', wilayaId: 5 },{ name: 'Ain Djasser', wilayaId: 5 },
  { name: 'Arris', wilayaId: 5 },{ name: 'Barika', wilayaId: 5 },{ name: 'Benzouh', wilayaId: 5 },
  { name: 'Bitam', wilayaId: 5 },{ name: 'Boulhilat', wilayaId: 5 },{ name: 'Boumagueur', wilayaId: 5 },
  { name: 'Chir', wilayaId: 5 },{ name: 'Djerma', wilayaId: 5 },{ name: 'El Hassi', wilayaId: 5 },
  { name: 'El Madher', wilayaId: 5 },{ name: 'Fesdis', wilayaId: 5 },{ name: 'Foum Toub', wilayaId: 5 },
  { name: 'Ghassira', wilayaId: 5 },{ name: 'Gosbat', wilayaId: 5 },{ name: 'Guigba', wilayaId: 5 },
  { name: 'Hidoussa', wilayaId: 5 },{ name: 'Ichmoul', wilayaId: 5 },{ name: 'Inoughissen', wilayaId: 5 },
  { name: 'Kimmel', wilayaId: 5 },{ name: 'Ksar Bellezma', wilayaId: 5 },{ name: 'Lazrou', wilayaId: 5 },
  { name: 'Lemsane', wilayaId: 5 },{ name: 'Maafa', wilayaId: 5 },{ name: 'Menaa', wilayaId: 5 },
  { name: 'Merouana', wilayaId: 5 },{ name: "N'Gaous", wilayaId: 5 },{ name: 'Oued Chaaba', wilayaId: 5 },
  { name: 'Oued El Ma', wilayaId: 5 },{ name: 'Ouled Aouf', wilayaId: 5 },{ name: 'Ouled Fadel', wilayaId: 5 },
  { name: 'Ouled Sellem', wilayaId: 5 },{ name: 'Ouled Si Slimane', wilayaId: 5 },
  { name: 'Ras El Aioun', wilayaId: 5 },{ name: 'Seggana', wilayaId: 5 },{ name: 'Seriana', wilayaId: 5 },
  { name: 'Tazoult', wilayaId: 5 },{ name: 'Teniet El Abed', wilayaId: 5 },{ name: 'Tighanimine', wilayaId: 5 },
  { name: 'Tilatou', wilayaId: 5 },{ name: 'Timgad', wilayaId: 5 },{ name: 'Zanat El Beida', wilayaId: 5 },
  { name: 'Boumia', wilayaId: 5 },{ name: 'Chemora', wilayaId: 5 },{ name: 'Oued Taga', wilayaId: 5 },
  { name: 'Talkhamt', wilayaId: 5 },{ name: 'Taxlent', wilayaId: 5 },{ name: 'Yabous', wilayaId: 5 },
  { name: 'Béjaïa', wilayaId: 6 },{ name: 'Amizour', wilayaId: 6 },{ name: 'Adekar', wilayaId: 6 },
  { name: 'Akbou', wilayaId: 6 },{ name: 'Aokas', wilayaId: 6 },{ name: 'Barbacha', wilayaId: 6 },
  { name: 'Beni Djellil', wilayaId: 6 },{ name: 'Beni Ksila', wilayaId: 6 },{ name: 'Beni Maouche', wilayaId: 6 },
  { name: 'Beni Mellikeche', wilayaId: 6 },{ name: 'Boudjellil', wilayaId: 6 },{ name: 'Bouhamza', wilayaId: 6 },
  { name: 'Boukhelifa', wilayaId: 6 },{ name: 'Chemini', wilayaId: 6 },{ name: 'Darguina', wilayaId: 6 },
  { name: 'Draâ El Kaïd', wilayaId: 6 },{ name: 'El Kseur', wilayaId: 6 },{ name: 'Fenaïa Ilmaten', wilayaId: 6 },
  { name: 'Ferroukha', wilayaId: 6 },{ name: 'Kendira', wilayaId: 6 },{ name: 'Kherrata', wilayaId: 6 },
  { name: 'Melbou', wilayaId: 6 },{ name: 'Oued Ghir', wilayaId: 6 },{ name: 'Ouzellaguen', wilayaId: 6 },
  { name: 'Seddouk', wilayaId: 6 },{ name: 'Sidi Ayad', wilayaId: 6 },{ name: 'Sidi Aich', wilayaId: 6 },
  { name: 'Sidi Ayad', wilayaId: 6 },{ name: 'Souk El Tenine', wilayaId: 6 },
  { name: 'Souk Oufella', wilayaId: 6 },{ name: 'Tala Hamza', wilayaId: 6 },{ name: 'Tamokra', wilayaId: 6 },
  { name: 'Tamridjet', wilayaId: 6 },{ name: 'Taourirt Ighil', wilayaId: 6 },{ name: 'Taskriout', wilayaId: 6 },
  { name: 'Tazmalt', wilayaId: 6 },{ name: 'Tibane', wilayaId: 6 },{ name: 'Tichy', wilayaId: 6 },
  { name: 'Tifra', wilayaId: 6 },{ name: 'Timezrit', wilayaId: 6 },{ name: 'Tinebdar', wilayaId: 6 },
  { name: "Tizi N'Berber", wilayaId: 6 },{ name: 'Toudja', wilayaId: 6 },{ name: 'Aït Rizine', wilayaId: 6 },
  { name: 'Aït Smail', wilayaId: 6 },{ name: 'Béni Mansour', wilayaId: 6 },{ name: 'Leflaye', wilayaId: 6 },
  { name: "M'cisna", wilayaId: 6 },{ name: 'Scrara', wilayaId: 6 },{ name: 'Biskra', wilayaId: 7 },
  { name: 'Ain Naga', wilayaId: 7 },{ name: 'Ain Zaatout', wilayaId: 7 },{ name: 'Bouchagroune', wilayaId: 7 },
  { name: 'Chetma', wilayaId: 7 },{ name: 'Djemorah', wilayaId: 7 },{ name: 'El Feidh', wilayaId: 7 },
  { name: 'El Ghrous', wilayaId: 7 },{ name: 'El Hadjeb', wilayaId: 7 },{ name: 'El Kantara', wilayaId: 7 },
  { name: 'El Outaya', wilayaId: 7 },{ name: 'Foughala', wilayaId: 7 },{ name: 'Khenguet Sidi Nadji', wilayaId: 7 },
  { name: 'Lichana', wilayaId: 7 },{ name: 'Lioua', wilayaId: 7 },{ name: "M'Chouneche", wilayaId: 7 },
  { name: 'Mekhadma', wilayaId: 7 },{ name: 'Meziraa', wilayaId: 7 },{ name: "M'Lili", wilayaId: 7 },
  { name: 'Oumache', wilayaId: 7 },{ name: 'Sidi Khaled', wilayaId: 7 },{ name: 'Sidi Okba', wilayaId: 7 },
  { name: 'Tolga', wilayaId: 7 },{ name: 'Zeribet El Oued', wilayaId: 7 },{ name: 'Béchar', wilayaId: 8 },
  { name: 'Abadla', wilayaId: 8 },{ name: 'Béni Abbès', wilayaId: 8 },{ name: 'Béni Ikhlef', wilayaId: 8 },
  { name: 'Béni Ounif', wilayaId: 8 },{ name: 'Boukais', wilayaId: 8 },{ name: 'El Ouata', wilayaId: 8 },
  { name: 'Erg Ferradj', wilayaId: 8 },{ name: 'Igli', wilayaId: 8 },{ name: 'Kenadsa', wilayaId: 8 },
  { name: 'Kerzaz', wilayaId: 8 },{ name: 'Ksabi', wilayaId: 8 },{ name: 'Lahmar', wilayaId: 8 },
  { name: 'Machraa Houari Boumedienne', wilayaId: 8 },{ name: 'Meridja', wilayaId: 8 },
  { name: 'Mogheul', wilayaId: 8 },{ name: 'Ouled Khoudir', wilayaId: 8 },{ name: 'Tabelbala', wilayaId: 8 },
  { name: 'Taghit', wilayaId: 8 },{ name: 'Tamtert', wilayaId: 8 },{ name: 'Timoudi', wilayaId: 8 },
  { name: 'Blida', wilayaId: 9 },{ name: 'Ain Romana', wilayaId: 9 },{ name: 'Beni Mered', wilayaId: 9 },
  { name: 'Beni Tamou', wilayaId: 9 },{ name: 'Benkhelil', wilayaId: 9 },{ name: 'Bouarfa', wilayaId: 9 },
  { name: 'Boufarik', wilayaId: 9 },{ name: 'Bougara', wilayaId: 9 },{ name: 'Bouinan', wilayaId: 9 },
  { name: 'Chebli', wilayaId: 9 },{ name: 'Chiffa', wilayaId: 9 },{ name: 'Chrea', wilayaId: 9 },
  { name: 'Djebabra', wilayaId: 9 },{ name: 'El Affroun', wilayaId: 9 },{ name: 'Guerrouaou', wilayaId: 9 },
  { name: 'Hammam Elouane', wilayaId: 9 },{ name: 'Larbaa', wilayaId: 9 },{ name: 'Meftah', wilayaId: 9 },
  { name: 'Mouzaia', wilayaId: 9 },{ name: 'Oued Alleug', wilayaId: 9 },{ name: 'Ouled Selama', wilayaId: 9 },
  { name: 'Ouled Yaich', wilayaId: 9 },{ name: 'Souhane', wilayaId: 9 },{ name: 'Soumaa', wilayaId: 9 },
  { name: 'Ain Bessem', wilayaId: 10 },{ name: 'Aghbalou', wilayaId: 10 },{ name: 'Ain El Hadjar', wilayaId: 10 },
  { name: 'Ahl El Ksar', wilayaId: 10 },{ name: 'Ain Laloui', wilayaId: 10 },{ name: 'Ath Mansour', wilayaId: 10 },
  { name: 'Aomar', wilayaId: 10 },{ name: 'Ain El Turc', wilayaId: 10 },{ name: 'Ait Laziz', wilayaId: 10 },
  { name: 'Bouderbala', wilayaId: 10 },{ name: 'Bechloul', wilayaId: 10 },{ name: 'Bir Ghbalou', wilayaId: 10 },
  { name: 'Boukram', wilayaId: 10 },{ name: 'Bordj Okhriss', wilayaId: 10 },{ name: 'Bouira', wilayaId: 10 },
  { name: 'Chorfa', wilayaId: 10 },{ name: 'Dechmia', wilayaId: 10 },{ name: 'Dirrah', wilayaId: 10 },
  { name: 'Djebahia', wilayaId: 10 },{ name: 'El Hakimia', wilayaId: 10 },{ name: 'El Hachimia', wilayaId: 10 },
  { name: 'El Adjiba', wilayaId: 10 },{ name: 'El Khabouzia', wilayaId: 10 },{ name: 'El Mokrani', wilayaId: 10 },
  { name: 'El Asnam', wilayaId: 10 },{ name: 'Guerrouma', wilayaId: 10 },{ name: 'Haizer', wilayaId: 10 },
  { name: 'Hadjera Zerga', wilayaId: 10 },{ name: 'Kadiria', wilayaId: 10 },{ name: 'Lakhdaria', wilayaId: 10 },
  { name: "M'Chedallah", wilayaId: 10 },{ name: 'Mezdour', wilayaId: 10 },{ name: 'Maala', wilayaId: 10 },
  { name: 'Maamora', wilayaId: 10 },{ name: 'Oued El Berdi', wilayaId: 10 },{ name: 'Ouled Rached', wilayaId: 10 },
  { name: 'Raouraoua', wilayaId: 10 },{ name: 'Ridane', wilayaId: 10 },{ name: 'Saharidj', wilayaId: 10 },
  { name: 'Sour El Ghouzlane', wilayaId: 10 },{ name: 'Souk El Khemis', wilayaId: 10 },
  { name: 'Taguedit', wilayaId: 10 },{ name: 'Taghzout', wilayaId: 10 },{ name: 'Zbarbar', wilayaId: 10 },
  { name: 'Tamanrasset', wilayaId: 11 },{ name: 'Abalessa', wilayaId: 11 },{ name: 'Idles', wilayaId: 11 },
  { name: 'Tazrouk', wilayaId: 11 },{ name: 'Ain Amguel', wilayaId: 11 },{ name: 'Tébessa', wilayaId: 12 },
  { name: 'Bir el-Ater', wilayaId: 12 },{ name: 'Cheria', wilayaId: 12 },{ name: 'Stah Guentis', wilayaId: 12 },
  { name: 'El Aouinet', wilayaId: 12 },{ name: 'El Houidjbet', wilayaId: 12 },
  { name: 'Safsaf El Ouesra', wilayaId: 12 },{ name: 'Hammamet', wilayaId: 12 },{ name: 'Negrine', wilayaId: 12 },
  { name: 'Bir Mokkadem', wilayaId: 12 },{ name: 'El Kouif', wilayaId: 12 },{ name: 'Morsott', wilayaId: 12 },
  { name: 'El Ogla', wilayaId: 12 },{ name: 'Bir Dheb', wilayaId: 12 },{ name: 'Ogla Melha', wilayaId: 12 },
  { name: 'Guorriguer', wilayaId: 12 },{ name: 'Bekkaria', wilayaId: 12 },{ name: 'Boukhadra', wilayaId: 12 },
  { name: 'Ouenza', wilayaId: 12 },{ name: 'El Ma Labiodh', wilayaId: 12 },{ name: 'Oum Ali', wilayaId: 12 },
  { name: 'Tlidjene', wilayaId: 12 },{ name: 'Ain Zerga', wilayaId: 12 },{ name: 'El Meridj', wilayaId: 12 },
  { name: 'Boulhaf Dir', wilayaId: 12 },{ name: 'Bedjene', wilayaId: 12 },{ name: 'El Mezeraa', wilayaId: 12 },
  { name: 'Ferkane', wilayaId: 12 },{ name: 'Tlemcen', wilayaId: 13 },{ name: 'Beni Mester', wilayaId: 13 },
  { name: 'Ain Tallout', wilayaId: 13 },{ name: 'Remchi', wilayaId: 13 },{ name: 'El Fehoul', wilayaId: 13 },
  { name: 'Sabra', wilayaId: 13 },{ name: 'Ghazaouet', wilayaId: 13 },{ name: 'Souani', wilayaId: 13 },
  { name: 'Djebala', wilayaId: 13 },{ name: 'El Gor', wilayaId: 13 },{ name: 'Oued Lakhdar', wilayaId: 13 },
  { name: 'Ain Fezza', wilayaId: 13 },{ name: 'Ouled Mimoun', wilayaId: 13 },{ name: 'Amieur', wilayaId: 13 },
  { name: 'Ain Youcef', wilayaId: 13 },{ name: 'Zenata', wilayaId: 13 },{ name: 'Beni Snous', wilayaId: 13 },
  { name: 'Bab El Assa', wilayaId: 13 },{ name: 'Dar Yaghmouracene', wilayaId: 13 },
  { name: 'Fellaoucene', wilayaId: 13 },{ name: 'Azails', wilayaId: 13 },{ name: 'Sebaa Chioukh', wilayaId: 13 },
  { name: 'Terny Beni Hdiel', wilayaId: 13 },{ name: 'Bensekrane', wilayaId: 13 },
  { name: 'Ain Nehala', wilayaId: 13 },{ name: 'Hennaya', wilayaId: 13 },{ name: 'Maghnia', wilayaId: 13 },
  { name: 'Hammam Boughrara', wilayaId: 13 },{ name: 'Souahlia', wilayaId: 13 },
  { name: 'MSirda Fouaga', wilayaId: 13 },{ name: 'Ain Fetah', wilayaId: 13 },{ name: 'El Aricha', wilayaId: 13 },
  { name: 'Souk Tlata', wilayaId: 13 },{ name: 'Sidi Abdelli', wilayaId: 13 },{ name: 'Sebdou', wilayaId: 13 },
  { name: 'Beni Ouarsous', wilayaId: 13 },{ name: 'Sidi Medjahed', wilayaId: 13 },
  { name: 'Beni Boussaid', wilayaId: 13 },{ name: "Marsa Ben M'Hidi", wilayaId: 13 },
  { name: 'Nedroma', wilayaId: 13 },{ name: 'Sidi Djillali', wilayaId: 13 },{ name: 'Beni Bahdel', wilayaId: 13 },
  { name: 'El Bouihi', wilayaId: 13 },{ name: 'Honaïne', wilayaId: 13 },{ name: 'Tienet', wilayaId: 13 },
  { name: 'Ouled Riyah', wilayaId: 13 },{ name: 'Bouhlou', wilayaId: 13 },{ name: 'Beni Khellad', wilayaId: 13 },
  { name: 'Ain Ghoraba', wilayaId: 13 },{ name: 'Chetouane', wilayaId: 13 },{ name: 'Mansourah', wilayaId: 13 },
  { name: 'Beni Semiel', wilayaId: 13 },{ name: 'Ain Kebira', wilayaId: 13 },
  { name: 'Ain Bouchekif', wilayaId: 14 },{ name: 'Ain Deheb', wilayaId: 14 },
  { name: 'Ain El Hadid', wilayaId: 14 },{ name: 'Ain Kermes', wilayaId: 14 },{ name: 'Ain Dzarit', wilayaId: 14 },
  { name: 'Bougara', wilayaId: 14 },{ name: 'Chehaima', wilayaId: 14 },{ name: 'Dahmouni', wilayaId: 14 },
  { name: 'Djebilet Rosfa', wilayaId: 14 },{ name: 'Djillali Ben Amar', wilayaId: 14 },
  { name: 'Faidja', wilayaId: 14 },{ name: 'Frenda', wilayaId: 14 },{ name: 'Guertoufa', wilayaId: 14 },
  { name: 'Madna', wilayaId: 14 },{ name: 'Mahdia', wilayaId: 14 },{ name: 'Mechraa Safa', wilayaId: 14 },
  { name: 'Medrissa', wilayaId: 14 },{ name: 'Medroussa', wilayaId: 14 },{ name: 'Meghila', wilayaId: 14 },
  { name: 'Mellakou', wilayaId: 14 },{ name: 'Nadorah', wilayaId: 14 },{ name: 'Naima', wilayaId: 14 },
  { name: 'Oued Lilli', wilayaId: 14 },{ name: 'Rahouia', wilayaId: 14 },{ name: 'Sebaine', wilayaId: 14 },
  { name: 'Sebt', wilayaId: 14 },{ name: 'Si Abdelghani', wilayaId: 14 },{ name: 'Sidi Abderahmane', wilayaId: 14 },
  { name: 'Sidi Ali Mellal', wilayaId: 14 },{ name: 'Sidi Bakhti', wilayaId: 14 },
  { name: 'Sidi Hosni', wilayaId: 14 },{ name: 'Sougueur', wilayaId: 14 },{ name: 'Tagdemt', wilayaId: 14 },
  { name: 'Takhemaret', wilayaId: 14 },{ name: 'Tiaret', wilayaId: 14 },{ name: 'Tidda', wilayaId: 14 },
  { name: 'Tousnina', wilayaId: 14 },{ name: 'Ksar Chellala', wilayaId: 14 },{ name: 'Hamadia', wilayaId: 14 },
  { name: 'Rechaiga', wilayaId: 14 },{ name: 'Serghine', wilayaId: 14 },
  { name: 'Zmalet El Emir Abdelkader', wilayaId: 14 },{ name: 'Tizi Ouzou', wilayaId: 15 },
  { name: 'Ain El Hammam', wilayaId: 15 },{ name: 'Akbil', wilayaId: 15 },{ name: 'Freha', wilayaId: 15 },
  { name: 'Souamaa', wilayaId: 15 },{ name: 'Mechtras', wilayaId: 15 },{ name: 'Irdjen', wilayaId: 15 },
  { name: 'Timizart', wilayaId: 15 },{ name: 'Makouda', wilayaId: 15 },{ name: 'Draa El Mizan', wilayaId: 15 },
  { name: 'Tizi Gheniff', wilayaId: 15 },{ name: 'Bounouh', wilayaId: 15 },{ name: 'Ait Chafaa', wilayaId: 15 },
  { name: 'Frikat', wilayaId: 15 },{ name: 'Ait Aissi', wilayaId: 15 },{ name: 'Ait Zmenzer', wilayaId: 15 },
  { name: 'Iferhounene', wilayaId: 15 },{ name: 'Azazga', wilayaId: 15 },{ name: 'Illoula Oumalou', wilayaId: 15 },
  { name: 'Yakouren', wilayaId: 15 },{ name: 'Larbaa Nath Irathen', wilayaId: 15 },
  { name: 'Tizi Rached', wilayaId: 15 },{ name: 'Zekri', wilayaId: 15 },{ name: 'Ouaguenoun', wilayaId: 15 },
  { name: 'Ain Zaouia', wilayaId: 15 },{ name: 'Imkiren', wilayaId: 15 },{ name: 'Ait Yahia', wilayaId: 15 },
  { name: 'Ait Mahmoud', wilayaId: 15 },{ name: 'Maatkas', wilayaId: 15 },{ name: 'Ait Boumahdi', wilayaId: 15 },
  { name: 'Abi Youcef', wilayaId: 15 },{ name: 'Beni Douala', wilayaId: 15 },{ name: 'Illilten', wilayaId: 15 },
  { name: 'Bouzeguene', wilayaId: 15 },{ name: 'Ait Aggouacha', wilayaId: 15 },{ name: 'Ouadhia', wilayaId: 15 },
  { name: 'Azeffoun', wilayaId: 15 },{ name: 'Tigzirt', wilayaId: 15 },{ name: 'Ait Aissa Mimoun', wilayaId: 15 },
  { name: 'Boghni', wilayaId: 15 },{ name: 'Ifigha', wilayaId: 15 },{ name: 'Ait Oumalou', wilayaId: 15 },
  { name: 'Tirmitine', wilayaId: 15 },{ name: 'Akerrou', wilayaId: 15 },{ name: 'Yatafen', wilayaId: 15 },
  { name: 'Ath Zikki', wilayaId: 15 },{ name: 'Draa Ben Khedda', wilayaId: 15 },
  { name: 'Ait Ouacif', wilayaId: 15 },{ name: 'Idjeur', wilayaId: 15 },{ name: 'Mekla', wilayaId: 15 },
  { name: "Tizi N'Tleta", wilayaId: 15 },{ name: 'Ait Yenni', wilayaId: 15 },{ name: 'Aghribs', wilayaId: 15 },
  { name: 'Iflissen', wilayaId: 15 },{ name: 'Boudjima', wilayaId: 15 },{ name: 'Ait Yahia Moussa', wilayaId: 15 },
  { name: 'Souk El Thenine', wilayaId: 15 },{ name: 'Ait Khellili', wilayaId: 15 },
  { name: 'Sidi Namane', wilayaId: 15 },{ name: 'Iboudraren', wilayaId: 15 },
  { name: 'Agouni Gueghrane', wilayaId: 15 },{ name: 'Mizrana', wilayaId: 15 },{ name: 'Imsouhel', wilayaId: 15 },
  { name: 'Tadmait', wilayaId: 15 },{ name: 'Ait Bouaddou', wilayaId: 15 },{ name: 'Assi Youcef', wilayaId: 15 },
  { name: 'Ait Toudert', wilayaId: 15 },{ name: 'Alger-Centre', wilayaId: 16 },{ name: "Sidi M'Hamed", wilayaId: 16 },
  { name: 'El Madania', wilayaId: 16 },{ name: 'Belouizdad', wilayaId: 16 },{ name: 'Hussein Dey', wilayaId: 16 },
  { name: 'Bab El Oued', wilayaId: 16 },{ name: 'Bologhine', wilayaId: 16 },{ name: 'Casbah', wilayaId: 16 },
  { name: 'Oued Koriche', wilayaId: 16 },{ name: 'Bir Mourad Rais', wilayaId: 16 },
  { name: 'El Biar', wilayaId: 16 },{ name: 'Bouzareah', wilayaId: 16 },{ name: 'Birkhadem', wilayaId: 16 },
  { name: 'El Harrach', wilayaId: 16 },{ name: 'Baraki', wilayaId: 16 },{ name: 'Oued Smar', wilayaId: 16 },
  { name: 'Kouba', wilayaId: 16 },{ name: 'Dar El Beida', wilayaId: 16 },{ name: 'Bab Ezzouar', wilayaId: 16 },
  { name: 'Ben Aknoun', wilayaId: 16 },{ name: 'Dely Ibrahim', wilayaId: 16 },{ name: 'Cheraga', wilayaId: 16 },
  { name: 'Hammamet', wilayaId: 16 },{ name: 'Rais Hamidou', wilayaId: 16 },{ name: 'Hydra', wilayaId: 16 },
  { name: 'Mohammadia', wilayaId: 16 },{ name: 'Bordj El Kiffan', wilayaId: 16 },
  { name: 'El Magharia', wilayaId: 16 },{ name: 'Beni Messous', wilayaId: 16 },
  { name: 'Les Eucalyptus', wilayaId: 16 },{ name: 'Birtouta', wilayaId: 16 },
  { name: 'Tessala El Merdja', wilayaId: 16 },{ name: 'Ouled Chebel', wilayaId: 16 },
  { name: 'Sidi Moussa', wilayaId: 16 },{ name: 'Ain Taya', wilayaId: 16 },{ name: 'Bordj El Bahri', wilayaId: 16 },
  { name: 'El Marsa', wilayaId: 16 },{ name: "H'raoua", wilayaId: 16 },{ name: 'Rouiba', wilayaId: 16 },
  { name: 'Reghaia', wilayaId: 16 },{ name: 'Ain Benian', wilayaId: 16 },{ name: 'Staoueli', wilayaId: 16 },
  { name: 'Zeralda', wilayaId: 16 },{ name: 'Mahelma', wilayaId: 16 },{ name: 'Rahmania', wilayaId: 16 },
  { name: 'Souidania', wilayaId: 16 },{ name: 'Ouled Fayet', wilayaId: 16 },{ name: 'El Achour', wilayaId: 16 },
  { name: 'Draria', wilayaId: 16 },{ name: 'Douera', wilayaId: 16 },{ name: 'Baba Hassen', wilayaId: 16 },
  { name: 'Khraicia', wilayaId: 16 },{ name: 'Saoula', wilayaId: 16 },{ name: 'Ain Chouhada', wilayaId: 17 },
  { name: 'Ain El Ibel', wilayaId: 17 },{ name: 'Ain Maabed', wilayaId: 17 },{ name: 'Beni Yagoub', wilayaId: 17 },
  { name: 'Charef', wilayaId: 17 },{ name: 'Dar Chioukh', wilayaId: 17 },{ name: 'Djelfa', wilayaId: 17 },
  { name: 'Douis', wilayaId: 17 },{ name: 'El Guedid', wilayaId: 17 },{ name: 'El Idrissia', wilayaId: 17 },
  { name: 'Hassi Bahbah', wilayaId: 17 },{ name: 'Hassi El Euch', wilayaId: 17 },{ name: "M'Liliha", wilayaId: 17 },
  { name: 'Moudjebara', wilayaId: 17 },{ name: 'Sidi Baizid', wilayaId: 17 },{ name: 'Tadmit', wilayaId: 17 },
  { name: 'Zaafrane', wilayaId: 17 },{ name: 'Ain Oussara', wilayaId: 17 },{ name: 'Birine', wilayaId: 17 },
  { name: 'Bouira Lahdab', wilayaId: 17 },{ name: 'El Khemis', wilayaId: 17 },{ name: 'Sidi Ladjel', wilayaId: 17 },
  { name: 'Had-Sahary', wilayaId: 17 },{ name: 'Guernini', wilayaId: 17 },{ name: 'Benhar', wilayaId: 17 },
  { name: 'Hassi Fedoul', wilayaId: 17 },{ name: 'Ain Feka', wilayaId: 17 },{ name: 'Messaad', wilayaId: 17 },
  { name: 'Sed Rahal', wilayaId: 17 },{ name: 'Faidh El Botma', wilayaId: 17 },{ name: 'Guettara', wilayaId: 17 },
  { name: 'Selmana', wilayaId: 17 },{ name: 'Oum Laadham', wilayaId: 17 },{ name: 'Deldoul', wilayaId: 17 },
  { name: 'Amourah', wilayaId: 17 },{ name: 'Jijel', wilayaId: 18 },{ name: 'Eraguene', wilayaId: 18 },
  { name: 'El Aouana', wilayaId: 18 },{ name: 'Ziama Mansouriah', wilayaId: 18 },{ name: 'Taher', wilayaId: 18 },
  { name: 'Emir Abdelkader', wilayaId: 18 },{ name: 'Chekfa', wilayaId: 18 },{ name: 'Chahna', wilayaId: 18 },
  { name: 'El Milia', wilayaId: 18 },{ name: 'Sidi Maarouf', wilayaId: 18 },{ name: 'Settara', wilayaId: 18 },
  { name: 'El Ancer', wilayaId: 18 },{ name: 'Sidi Abdelaziz', wilayaId: 18 },{ name: 'Kaous', wilayaId: 18 },
  { name: 'Ghebala', wilayaId: 18 },{ name: 'Bouraoui Belhadef', wilayaId: 18 },{ name: 'Djimla', wilayaId: 18 },
  { name: 'Selma Benziada', wilayaId: 18 },{ name: 'Boucif Ouled Askeur', wilayaId: 18 },
  { name: 'El Kennar Nouchfi', wilayaId: 18 },{ name: 'Ouled Yahia Khedrouche', wilayaId: 18 },
  { name: 'Boudriaa Ben Yadjis', wilayaId: 18 },{ name: 'Kheiri Oued Adjoul', wilayaId: 18 },
  { name: 'Texenna', wilayaId: 18 },{ name: 'Djemaa Beni Habibi', wilayaId: 18 },
  { name: 'Bordj Tahar', wilayaId: 18 },{ name: 'Ouled Rabah', wilayaId: 18 },{ name: 'Ouadjana', wilayaId: 18 },
  { name: 'Ain Abessa', wilayaId: 19 },{ name: 'Ain Arnat', wilayaId: 19 },{ name: 'Ain Azel', wilayaId: 19 },
  { name: 'Ain El Kebira', wilayaId: 19 },{ name: 'Ain Lahdjar', wilayaId: 19 },
  { name: 'Ain Legradj', wilayaId: 19 },{ name: 'Ain Oulmene', wilayaId: 19 },{ name: 'Ain Roua', wilayaId: 19 },
  { name: 'Ain Sebt', wilayaId: 19 },{ name: 'Ait Naoual Mezada', wilayaId: 19 },{ name: 'Ait Tizi', wilayaId: 19 },
  { name: 'Beni Ouartilene', wilayaId: 19 },{ name: 'Amoucha', wilayaId: 19 },{ name: 'Babor', wilayaId: 19 },
  { name: 'Bazer Sakhra', wilayaId: 19 },{ name: 'Beidha Bordj', wilayaId: 19 },{ name: 'Belaa', wilayaId: 19 },
  { name: 'Beni Aziz', wilayaId: 19 },{ name: 'Beni Chebana', wilayaId: 19 },{ name: 'Beni Fouda', wilayaId: 19 },
  { name: 'Beni Hocine', wilayaId: 19 },{ name: 'Beni Mouhli', wilayaId: 19 },
  { name: 'Bir El Arch', wilayaId: 19 },{ name: 'Bir Haddada', wilayaId: 19 },{ name: 'Bouandas', wilayaId: 19 },
  { name: 'Bougaa', wilayaId: 19 },{ name: 'Bousselam', wilayaId: 19 },{ name: 'Boutaleb', wilayaId: 19 },
  { name: 'Dehamcha', wilayaId: 19 },{ name: 'Djemila', wilayaId: 19 },{ name: 'Draa Kebila', wilayaId: 19 },
  { name: 'El Eulma', wilayaId: 19 },{ name: 'El Ouldja', wilayaId: 19 },{ name: 'El Ouricia', wilayaId: 19 },
  { name: 'Guellal', wilayaId: 19 },{ name: 'Guelta Zerka', wilayaId: 19 },{ name: 'Guenzet', wilayaId: 19 },
  { name: 'Guidjel', wilayaId: 19 },{ name: 'Hamma', wilayaId: 19 },{ name: 'Hammam Guergour', wilayaId: 19 },
  { name: 'Hammam Soukhna', wilayaId: 19 },{ name: 'Harbil', wilayaId: 19 },{ name: 'Ksar El Abtal', wilayaId: 19 },
  { name: 'Maaouia', wilayaId: 19 },{ name: 'Maoklane', wilayaId: 19 },{ name: 'Mezloug', wilayaId: 19 },
  { name: 'Oued El Barad', wilayaId: 19 },{ name: 'Ouled Addouane', wilayaId: 19 },
  { name: 'Ouled Sabor', wilayaId: 19 },{ name: 'Ouled Si Ahmed', wilayaId: 19 },
  { name: 'Ouled Tebben', wilayaId: 19 },{ name: 'Rasfa', wilayaId: 19 },{ name: 'Salah Bey', wilayaId: 19 },
  { name: 'Serdj El Ghoul', wilayaId: 19 },{ name: 'Setif', wilayaId: 19 },{ name: 'Tachouda', wilayaId: 19 },
  { name: 'Talaifacene', wilayaId: 19 },{ name: 'Taya', wilayaId: 19 },{ name: 'Tella', wilayaId: 19 },
  { name: "Tizi N'Bechar", wilayaId: 19 },
  { name: 'Ain El Hadjar', wilayaId: 20 },{ name: 'Ain Sekhouna', wilayaId: 20 },
  { name: 'Ain Soltane', wilayaId: 20 },{ name: 'Doui Thabet', wilayaId: 20 },
  { name: 'El Hassasna', wilayaId: 20 },{ name: 'Hounet', wilayaId: 20 },{ name: 'Maamora', wilayaId: 20 },
  { name: 'Moulay Larbi', wilayaId: 20 },{ name: 'Ouled Brahim', wilayaId: 20 },
  { name: 'Ouled Khaled', wilayaId: 20 },{ name: 'Saida', wilayaId: 20 },{ name: 'Sidi Ahmed', wilayaId: 20 },
  { name: 'Sidi Amar', wilayaId: 20 },{ name: 'Sidi Boubekeur', wilayaId: 20 },{ name: 'Tircine', wilayaId: 20 },
  { name: 'Youb', wilayaId: 20 },{ name: 'Ain Bouziane', wilayaId: 21 },{ name: 'Ain Charchar', wilayaId: 21 },
  { name: 'Ain Kechra', wilayaId: 21 },{ name: 'Ain Zouit', wilayaId: 21 },{ name: 'Azzaba', wilayaId: 21 },
  { name: 'Bekkouche Lakhdar', wilayaId: 21 },{ name: 'Bin El Ouiden', wilayaId: 21 },
  { name: 'Ben Azzouz', wilayaId: 21 },{ name: 'Beni Bechir', wilayaId: 21 },
  { name: 'Beni Oulbane', wilayaId: 21 },{ name: 'Beni Zid', wilayaId: 21 },{ name: 'Bouchtata', wilayaId: 21 },
  { name: 'Cheraia', wilayaId: 21 },{ name: 'Collo', wilayaId: 21 },
  { name: 'Djendel Saadi Mohamed', wilayaId: 21 },{ name: 'El Ghedir', wilayaId: 21 },
  { name: 'El Hadaiek', wilayaId: 21 },{ name: 'El Harrouch', wilayaId: 21 },{ name: 'El Marsa', wilayaId: 21 },
  { name: 'Emdjez Edchich', wilayaId: 21 },{ name: 'Es Sebt', wilayaId: 21 },{ name: 'Filfila', wilayaId: 21 },
  { name: 'Hamadi Krouma', wilayaId: 21 },{ name: 'Kanoua', wilayaId: 21 },{ name: 'Kerkera', wilayaId: 21 },
  { name: 'Kheneg Mayoum', wilayaId: 21 },{ name: 'Oued Zehour', wilayaId: 21 },
  { name: 'Ouldja Boulballout', wilayaId: 21 },{ name: 'Ouled Attia', wilayaId: 21 },
  { name: 'Ouled Hbaba', wilayaId: 21 },{ name: 'Oum Toub', wilayaId: 21 },
  { name: 'Ramdane Djamel', wilayaId: 21 },{ name: 'Salah Bouchaour', wilayaId: 21 },
  { name: 'Sidi Mezghiche', wilayaId: 21 },{ name: 'Skikda', wilayaId: 21 },{ name: 'Tamalous', wilayaId: 21 },
  { name: 'Zerdaza', wilayaId: 21 },{ name: 'Zitouna', wilayaId: 21 },{ name: 'Ain Adden', wilayaId: 22 },
  { name: 'Ain El Berd', wilayaId: 22 },{ name: 'Ain Kada', wilayaId: 22 },{ name: 'Ain Thrid', wilayaId: 22 },
  { name: 'Ain Tindamine', wilayaId: 22 },{ name: 'Amarnas', wilayaId: 22 },
  { name: 'Badredine El Mokrani', wilayaId: 22 },{ name: 'Belarbi', wilayaId: 22 },
  { name: 'Ben Badis', wilayaId: 22 },{ name: 'Benachiba Chelia', wilayaId: 22 },
  { name: 'Bir El Hammam', wilayaId: 22 },{ name: 'Boudjebaa El Bordj', wilayaId: 22 },
  { name: 'Boukhanafis', wilayaId: 22 },{ name: 'Chettouane Belaila', wilayaId: 22 },
  { name: 'Dhaya', wilayaId: 22 },{ name: 'El Hacaiba', wilayaId: 22 },{ name: 'Hassi Dahou', wilayaId: 22 },
  { name: 'Hassi Zehana', wilayaId: 22 },{ name: 'Lamtar', wilayaId: 22 },{ name: 'Makedra', wilayaId: 22 },
  { name: 'Marhoum', wilayaId: 22 },{ name: "M'Cid", wilayaId: 22 },{ name: 'Merine', wilayaId: 22 },
  { name: 'Mezaourou', wilayaId: 22 },{ name: 'Mostefa Ben Brahim', wilayaId: 22 },
  { name: 'Moulay Slissen', wilayaId: 22 },{ name: 'Oued Sebaa', wilayaId: 22 },
  { name: 'Oued Sefioun', wilayaId: 22 },{ name: 'Oued Taourira', wilayaId: 22 },
  { name: 'Ras El Ma', wilayaId: 22 },{ name: 'Redjem Demouche', wilayaId: 22 },
  { name: 'Sehala Thaoura', wilayaId: 22 },{ name: 'Sfisef', wilayaId: 22 },
  { name: 'Sidi Ali Benyoub', wilayaId: 22 },{ name: 'Sidi Ali Boussidi', wilayaId: 22 },
  { name: 'Sidi Bel Abbes', wilayaId: 22 },{ name: 'Sidi Brahim', wilayaId: 22 },
  { name: 'Sidi Hamadouche', wilayaId: 22 },{ name: 'Sidi Khaled', wilayaId: 22 },
  { name: 'Sidi Lahcene', wilayaId: 22 },{ name: 'Sidi Yacoub', wilayaId: 22 },{ name: 'Tabia', wilayaId: 22 },
  { name: 'Taoudmout', wilayaId: 22 },{ name: 'Telagh', wilayaId: 22 },{ name: 'Tenira', wilayaId: 22 },
  { name: 'Teghanif', wilayaId: 22 },{ name: 'Tessala', wilayaId: 22 },{ name: 'Tilmouni', wilayaId: 22 },
  { name: 'Zerouala', wilayaId: 22 },{ name: 'Annaba', wilayaId: 23 },{ name: 'Berrahal', wilayaId: 23 },
  { name: 'El Hadjar', wilayaId: 23 },{ name: 'Eulma', wilayaId: 23 },{ name: 'El Bouni', wilayaId: 23 },
  { name: 'Oued El Aneb', wilayaId: 23 },{ name: 'Cheurfa', wilayaId: 23 },{ name: 'Seraidi', wilayaId: 23 },
  { name: 'Ain Berda', wilayaId: 23 },{ name: 'Chetaibi', wilayaId: 23 },{ name: 'Sidi Amar', wilayaId: 23 },
  { name: 'Treat', wilayaId: 23 },{ name: 'Ain Ben Beida', wilayaId: 24 },{ name: 'Ain Larbi', wilayaId: 24 },
  { name: 'Ain Makhlouf', wilayaId: 24 },{ name: 'Ain Reggada', wilayaId: 24 },
  { name: 'Ain Sandel', wilayaId: 24 },{ name: 'Belkheir', wilayaId: 24 },{ name: 'Ben Djerrah', wilayaId: 24 },
  { name: 'Beni Mezline', wilayaId: 24 },{ name: 'Bordj Sabath', wilayaId: 24 },
  { name: 'Bouhachana', wilayaId: 24 },{ name: 'Bouhamdane', wilayaId: 24 },
  { name: 'Bouati Mahmoud', wilayaId: 24 },{ name: 'Bouchegouf', wilayaId: 24 },
  { name: 'Boumahra Ahmed', wilayaId: 24 },{ name: 'Dahouara', wilayaId: 24 },
  { name: 'Djeballah Khemissi', wilayaId: 24 },{ name: 'El Fedjoudj', wilayaId: 24 },
  { name: 'Guellat Bou Sbaa', wilayaId: 24 },{ name: 'Guelma', wilayaId: 24 },
  { name: 'Hammam Debagh', wilayaId: 24 },{ name: "Hammam N'Bail", wilayaId: 24 },
  { name: 'Heliopolis', wilayaId: 24 },{ name: 'Houari Boumediene', wilayaId: 24 },
  { name: 'Khezarra', wilayaId: 24 },{ name: 'Medjez Amar', wilayaId: 24 },{ name: 'Medjez Sfa', wilayaId: 24 },
  { name: 'Nechmaya', wilayaId: 24 },{ name: 'Oued Cheham', wilayaId: 24 },{ name: 'Oued Fragha', wilayaId: 24 },
  { name: 'Oued Zenati', wilayaId: 24 },{ name: 'Ras El Agba', wilayaId: 24 },{ name: 'Roknia', wilayaId: 24 },
  { name: 'Sellaoua Announa', wilayaId: 24 },{ name: 'Tamlouka', wilayaId: 24 },
  { name: 'Ouled Rahmoune', wilayaId: 25 },{ name: 'Ain Abid', wilayaId: 25 },{ name: 'El Khroub', wilayaId: 25 },
  { name: 'Ibn Badis', wilayaId: 25 },{ name: 'Ain Smara', wilayaId: 25 },{ name: 'Constantine', wilayaId: 25 },
  { name: 'Ibn Ziad', wilayaId: 25 },{ name: 'Hamma Bouziane', wilayaId: 25 },
  { name: 'Didouche Mourad', wilayaId: 25 },{ name: 'Messaoud Boudjriou', wilayaId: 25 },
  { name: 'Beni Hamiden', wilayaId: 25 },{ name: 'Zighoud Youcef', wilayaId: 25 },
  { name: 'Aissaouia', wilayaId: 26 },{ name: 'Baata', wilayaId: 26 },{ name: 'Benchicao', wilayaId: 26 },
  { name: 'Beni Slimane', wilayaId: 26 },{ name: 'Berrouaghia', wilayaId: 26 },
  { name: 'Bir Ben Laabed', wilayaId: 26 },{ name: 'Bouaichoune', wilayaId: 26 },
  { name: 'Bouchrahil', wilayaId: 26 },{ name: 'Bouskene', wilayaId: 26 },{ name: 'Deux Bassins', wilayaId: 26 },
  { name: 'Djouab', wilayaId: 26 },{ name: 'Draa Essamar', wilayaId: 26 },{ name: 'El Azizia', wilayaId: 26 },
  { name: 'El Guelb El Kebir', wilayaId: 26 },{ name: 'El Hamdania', wilayaId: 26 },
  { name: 'El Omaria', wilayaId: 26 },{ name: 'Hannacha', wilayaId: 26 },{ name: 'Khams Djouamaa', wilayaId: 26 },
  { name: 'Meghraoua', wilayaId: 26 },{ name: 'Medea', wilayaId: 26 },{ name: 'Moudjbar', wilayaId: 26 },
  { name: 'Mezerana', wilayaId: 26 },{ name: 'Mihoub', wilayaId: 26 },{ name: 'Ouamri', wilayaId: 26 },
  { name: 'Oued Harbil', wilayaId: 26 },{ name: 'Ouled Bouachra', wilayaId: 26 },
  { name: 'Ouled Brahim', wilayaId: 26 },{ name: 'Ouled Deide', wilayaId: 26 },{ name: 'Ouzera', wilayaId: 26 },
  { name: 'Rebaia', wilayaId: 26 },{ name: 'Sedraia', wilayaId: 26 },{ name: 'Seghouane', wilayaId: 26 },
  { name: 'Si Mahdjoub', wilayaId: 26 },{ name: 'Sidi Errabia', wilayaId: 26 },
  { name: 'Sidi Naamane', wilayaId: 26 },{ name: 'Sidi Zahar', wilayaId: 26 },{ name: 'Sidi Ziane', wilayaId: 26 },
  { name: 'Souagui', wilayaId: 26 },{ name: 'Tablat', wilayaId: 26 },{ name: 'Tamesguida', wilayaId: 26 },
  { name: 'Tizi Mahdi', wilayaId: 26 },{ name: 'Tlatet Eddouar', wilayaId: 26 },{ name: 'Zoubiria', wilayaId: 26 },
  { name: 'Ksar El Boukhari', wilayaId: 26 },{ name: 'Ain Boucif', wilayaId: 26 },
  { name: 'Ain Ouksir', wilayaId: 26 },{ name: 'Aziz', wilayaId: 26 },{ name: 'Bou Aiche', wilayaId: 26 },
  { name: 'Boughezoul', wilayaId: 26 },{ name: 'Boghar', wilayaId: 26 },{ name: 'Chahbounia', wilayaId: 26 },
  { name: 'Cheniguel', wilayaId: 26 },{ name: 'Chellalet El Adhaoura', wilayaId: 26 },
  { name: 'Derrag', wilayaId: 26 },{ name: 'El Ouinet', wilayaId: 26 },{ name: 'Kef Lakhdar', wilayaId: 26 },
  { name: 'Meftaha', wilayaId: 26 },{ name: 'Ouled Antar', wilayaId: 26 },{ name: 'Ouled Hellal', wilayaId: 26 },
  { name: 'Ouled Maaref', wilayaId: 26 },{ name: 'Oum El Djalil', wilayaId: 26 },{ name: 'Saneg', wilayaId: 26 },
  { name: 'Sidi Damed', wilayaId: 26 },{ name: 'Tafraout', wilayaId: 26 },
  { name: 'Abdelmalek Ramdane', wilayaId: 27 },{ name: 'Achaacha', wilayaId: 27 },
  { name: 'Ain Boudinar', wilayaId: 27 },{ name: 'Ain Nouissy', wilayaId: 27 },
  { name: 'Ain Sidi Cherif', wilayaId: 27 },{ name: 'Ain Tedles', wilayaId: 27 },
  { name: 'Blad Touahria', wilayaId: 27 },{ name: 'Bouguirat', wilayaId: 27 },
  { name: 'El Hassiane', wilayaId: 27 },{ name: 'Fornaka', wilayaId: 27 },{ name: 'Hadjadj', wilayaId: 27 },
  { name: 'Hassi Mameche', wilayaId: 27 },{ name: 'Khadra', wilayaId: 27 },{ name: 'Kheireddine', wilayaId: 27 },
  { name: 'Mansourah', wilayaId: 27 },{ name: 'Mesra', wilayaId: 27 },{ name: 'Mazagran', wilayaId: 27 },
  { name: 'Mostaganem', wilayaId: 27 },{ name: 'Nekmaria', wilayaId: 27 },{ name: 'Oued El Kheir', wilayaId: 27 },
  { name: 'Ouled Boughalem', wilayaId: 27 },{ name: 'Ouled Maallah', wilayaId: 27 },
  { name: 'Safsaf', wilayaId: 27 },{ name: 'Sayada', wilayaId: 27 },{ name: 'Sidi Ali', wilayaId: 27 },
  { name: 'Sidi Belattar', wilayaId: 27 },{ name: 'Sidi Lakhdar', wilayaId: 27 },{ name: 'Sirat', wilayaId: 27 },
  { name: 'Souaflia', wilayaId: 27 },{ name: 'Sour', wilayaId: 27 },{ name: 'Stidia', wilayaId: 27 },
  { name: 'Tazgait', wilayaId: 27 },{ name: 'Ain El Hadjel', wilayaId: 28 },{ name: 'Ain Khadra', wilayaId: 28 },
  { name: 'Belaiba', wilayaId: 28 },{ name: 'Beni Ilmane', wilayaId: 28 },{ name: 'Berhoum', wilayaId: 28 },
  { name: 'Bouti Sayah', wilayaId: 28 },{ name: 'Chellal', wilayaId: 28 },{ name: 'Dehahna', wilayaId: 28 },
  { name: 'Hammam Dhalaa', wilayaId: 28 },{ name: 'Khettouti Sed El Djir', wilayaId: 28 },
  { name: 'Maadid', wilayaId: 28 },{ name: 'Maarif', wilayaId: 28 },{ name: 'Magra', wilayaId: 28 },
  { name: "M'Sila", wilayaId: 28 },{ name: "M'Tarfa", wilayaId: 28 },{ name: 'Ouanougha', wilayaId: 28 },
  { name: 'Ouled Addi Guebala', wilayaId: 28 },{ name: 'Ouled Atia', wilayaId: 28 },
  { name: 'Ouled Derradj', wilayaId: 28 },{ name: 'Ouled Madhi', wilayaId: 28 },
  { name: 'Ouled Mansour', wilayaId: 28 },{ name: 'Sidi Aissa', wilayaId: 28 },
  { name: 'Sidi Hadjeres', wilayaId: 28 },{ name: 'Souamaa', wilayaId: 28 },{ name: 'Tarmount', wilayaId: 28 },
  { name: 'Ain El Melh', wilayaId: 28 },{ name: 'Ain Errich', wilayaId: 28 },{ name: 'Ain Fares', wilayaId: 28 },
  { name: 'Ben Srour', wilayaId: 28 },{ name: 'Benzouh', wilayaId: 28 },{ name: 'Bir Foda', wilayaId: 28 },
  { name: 'Bou Saada', wilayaId: 28 },{ name: 'Djebel Messaad', wilayaId: 28 },{ name: 'El Hamel', wilayaId: 28 },
  { name: 'El Houamed', wilayaId: 28 },{ name: 'Khoubana', wilayaId: 28 },{ name: "M'Cif", wilayaId: 28 },
  { name: 'Medjedel', wilayaId: 28 },{ name: 'Menaa', wilayaId: 28 },{ name: 'Mohammed Boudiaf', wilayaId: 28 },
  { name: 'Oultem', wilayaId: 28 },{ name: 'Ouled Sidi Brahim', wilayaId: 28 },
  { name: 'Ouled Slimane', wilayaId: 28 },{ name: 'Sidi Ameur', wilayaId: 28 },
  { name: "Sidi M'Hamed", wilayaId: 28 },{ name: 'Slim', wilayaId: 28 },{ name: 'Tamsa', wilayaId: 28 },
  { name: 'Zarzour', wilayaId: 28 },{ name: 'Ain Fares', wilayaId: 29 },{ name: 'Ain Fekan', wilayaId: 29 },
  { name: 'Ain Ferah', wilayaId: 29 },{ name: 'Ain Fras', wilayaId: 29 },{ name: 'Alaimia', wilayaId: 29 },
  { name: 'Aouf', wilayaId: 29 },{ name: 'Beniane', wilayaId: 29 },{ name: 'Bou Hanifia', wilayaId: 29 },
  { name: 'Bou Henni', wilayaId: 29 },{ name: 'Chorfa', wilayaId: 29 },{ name: 'El Bordj', wilayaId: 29 },
  { name: 'El Gaada', wilayaId: 29 },{ name: 'El Ghomri', wilayaId: 29 },{ name: 'El Guettana', wilayaId: 29 },
  { name: 'El Keurt', wilayaId: 29 },{ name: 'El Menaouer', wilayaId: 29 },{ name: 'Ferraguig', wilayaId: 29 },
  { name: 'Froha', wilayaId: 29 },{ name: 'Gharrous', wilayaId: 29 },{ name: 'Guerdjoum', wilayaId: 29 },
  { name: 'Ghriss', wilayaId: 29 },{ name: 'Hachem', wilayaId: 29 },{ name: 'Hacine', wilayaId: 29 },
  { name: 'Khalouia', wilayaId: 29 },{ name: 'Makdha', wilayaId: 29 },{ name: 'Mamounia', wilayaId: 29 },
  { name: 'Maoussa', wilayaId: 29 },{ name: 'Mascara', wilayaId: 29 },{ name: 'Matemore', wilayaId: 29 },
  { name: 'Mocta Douz', wilayaId: 29 },{ name: 'Mohammadia', wilayaId: 29 },{ name: 'Nesmoth', wilayaId: 29 },
  { name: 'Oggaz', wilayaId: 29 },{ name: 'Oued El Abtal', wilayaId: 29 },{ name: 'Oued Taria', wilayaId: 29 },
  { name: 'Ras El Ain Amirouche', wilayaId: 29 },{ name: 'Sedjerara', wilayaId: 29 },
  { name: 'Sehailia', wilayaId: 29 },{ name: 'Sidi Abdeldjebar', wilayaId: 29 },
  { name: 'Sidi Abdelmoumen', wilayaId: 29 },{ name: 'Sidi Kada', wilayaId: 29 },
  { name: 'Sidi Boussaid', wilayaId: 29 },{ name: 'Sig', wilayaId: 29 },{ name: 'Tighennif', wilayaId: 29 },
  { name: 'Tizi', wilayaId: 29 },{ name: 'Zahana', wilayaId: 29 },{ name: 'Zelmata', wilayaId: 29 },
  { name: 'Ain Beida', wilayaId: 30 },{ name: 'El Borma', wilayaId: 30 },
  { name: 'Hassi Ben Abdellah', wilayaId: 30 },{ name: 'Hassi Messaoud', wilayaId: 30 },
  { name: "N'Goussa", wilayaId: 30 },{ name: 'Ouargla', wilayaId: 30 },{ name: 'Rouissat', wilayaId: 30 },
  { name: 'Sidi Khouiled', wilayaId: 30 },{ name: 'Oran', wilayaId: 31 },{ name: 'Gdyel', wilayaId: 31 },
  { name: 'Bir El Djir', wilayaId: 31 },{ name: 'Hassi Bounif', wilayaId: 31 },{ name: 'Es Senia', wilayaId: 31 },
  { name: 'Arzew', wilayaId: 31 },{ name: 'Bethioua', wilayaId: 31 },{ name: 'Marsat El Hadjadj', wilayaId: 31 },
  { name: 'Ain El Turk', wilayaId: 31 },{ name: 'El Ancor', wilayaId: 31 },{ name: 'Oued Tlelat', wilayaId: 31 },
  { name: 'Tafraoui', wilayaId: 31 },{ name: 'Sidi Chami', wilayaId: 31 },{ name: 'Boufatis', wilayaId: 31 },
  { name: 'Mers El Kebir', wilayaId: 31 },{ name: 'Bousfer', wilayaId: 31 },{ name: 'El Kerma', wilayaId: 31 },
  { name: 'El Braya', wilayaId: 31 },{ name: 'Hassi Ben Okba', wilayaId: 31 },{ name: 'Ben Freha', wilayaId: 31 },
  { name: 'Hassi Mefsoukh', wilayaId: 31 },{ name: 'Sidi Benyebka', wilayaId: 31 },
  { name: 'Misserghin', wilayaId: 31 },{ name: 'Boutlelis', wilayaId: 31 },
  { name: 'Ain El Kerma', wilayaId: 31 },{ name: 'Ain El Bia', wilayaId: 31 },{ name: 'El Bayadh', wilayaId: 32 },
  { name: 'Rogassa', wilayaId: 32 },{ name: 'Stitten', wilayaId: 32 },{ name: 'Brezina', wilayaId: 32 },
  { name: 'Ghassoul', wilayaId: 32 },{ name: 'Boualem', wilayaId: 32 },
  { name: 'El Abiodh Sidi Cheikh', wilayaId: 32 },{ name: 'Ain El Orak', wilayaId: 32 },
  { name: 'Arbaouat', wilayaId: 32 },{ name: 'Bougtoub', wilayaId: 32 },{ name: 'El Kheiter', wilayaId: 32 },
  { name: 'Kef El Ahmar', wilayaId: 32 },{ name: 'Boussemghoun', wilayaId: 32 },
  { name: 'Chellala', wilayaId: 32 },{ name: 'Kraakda', wilayaId: 32 },{ name: 'El Bnoud', wilayaId: 32 },
  { name: 'Cheguig', wilayaId: 32 },{ name: 'Sidi Ameur', wilayaId: 32 },{ name: 'El Mehara', wilayaId: 32 },
  { name: 'Tousmouline', wilayaId: 32 },{ name: 'Sidi Slimane', wilayaId: 32 },
  { name: 'Sidi Tifour', wilayaId: 32 },{ name: 'Illizi', wilayaId: 33 },{ name: 'Debdeb', wilayaId: 33 },
  { name: 'Bordj Omar Driss', wilayaId: 33 },{ name: 'In Amenas', wilayaId: 33 },
  { name: 'Ain Taghrout', wilayaId: 34 },{ name: 'Ain Tesra', wilayaId: 34 },{ name: 'Belimour', wilayaId: 34 },
  { name: 'Ben Daoud', wilayaId: 34 },{ name: 'Bir Kasdali', wilayaId: 34 },
  { name: 'Bordj Bou Arreridj', wilayaId: 34 },{ name: 'Bordj Ghedir', wilayaId: 34 },
  { name: 'Bordj Zemoura', wilayaId: 34 },{ name: 'Colla', wilayaId: 34 },{ name: 'Djaafra', wilayaId: 34 },
  { name: 'El Ach', wilayaId: 34 },{ name: 'El Achir', wilayaId: 34 },{ name: 'El Anseur', wilayaId: 34 },
  { name: 'El Hamadia', wilayaId: 34 },{ name: 'El Main', wilayaId: 34 },{ name: "El M'hir", wilayaId: 34 },
  { name: 'Ghilassa', wilayaId: 34 },{ name: 'Haraza', wilayaId: 34 },{ name: 'Hasnaoua', wilayaId: 34 },
  { name: 'Khelil', wilayaId: 34 },{ name: 'Ksour', wilayaId: 34 },{ name: 'Mansoura', wilayaId: 34 },
  { name: 'Medjana', wilayaId: 34 },{ name: 'Ouled Brahem', wilayaId: 34 },
  { name: 'Ouled Dahmane', wilayaId: 34 },{ name: 'Ouled Sidi Brahim', wilayaId: 34 },
  { name: 'Rabta', wilayaId: 34 },{ name: 'Ras El Oued', wilayaId: 34 },{ name: 'Sidi Embarek', wilayaId: 34 },
  { name: 'Tefreg', wilayaId: 34 },{ name: 'Taglait', wilayaId: 34 },{ name: 'Teniet En Nasr', wilayaId: 34 },
  { name: 'Tassameurt', wilayaId: 34 },{ name: 'Tixter', wilayaId: 34 },{ name: 'Afir', wilayaId: 35 },
  { name: 'Ammal', wilayaId: 35 },{ name: 'Baghlia', wilayaId: 35 },{ name: 'Ben Choud', wilayaId: 35 },
  { name: 'Beni Amrane', wilayaId: 35 },{ name: 'Bordj Menaiel', wilayaId: 35 },
  { name: 'Boudouaou', wilayaId: 35 },{ name: 'Boudouaou-El-Bahri', wilayaId: 35 },
  { name: 'Boumerdes', wilayaId: 35 },{ name: 'Bouzegza Keddara', wilayaId: 35 },
  { name: 'Chabet el Ameur', wilayaId: 35 },{ name: 'Corso', wilayaId: 35 },{ name: 'Dellys', wilayaId: 35 },
  { name: 'Djinet', wilayaId: 35 },{ name: 'El Kharrouba', wilayaId: 35 },{ name: 'Hammedi', wilayaId: 35 },
  { name: 'Issers', wilayaId: 35 },{ name: 'Khemis El-Khechna', wilayaId: 35 },
  { name: 'Larbatache', wilayaId: 35 },{ name: 'Leghata', wilayaId: 35 },{ name: 'Naciria', wilayaId: 35 },
  { name: 'Ouled Aissa', wilayaId: 35 },{ name: 'Ouled Hedadj', wilayaId: 35 },
  { name: 'Ouled Moussa', wilayaId: 35 },{ name: 'Si Mustapha', wilayaId: 35 },
  { name: 'Sidi Daoud', wilayaId: 35 },{ name: 'Souk El Had', wilayaId: 35 },{ name: 'Taourga', wilayaId: 35 },
  { name: 'Thenia', wilayaId: 35 },{ name: 'Tidjelabine', wilayaId: 35 },{ name: 'Timezrit', wilayaId: 35 },
  { name: 'Zemmouri', wilayaId: 35 },{ name: 'Ain El Assel', wilayaId: 36 },{ name: 'Ain Kerma', wilayaId: 36 },
  { name: 'Asfour', wilayaId: 36 },{ name: 'Ben Mehidi', wilayaId: 36 },{ name: 'Berrihane', wilayaId: 36 },
  { name: 'Besbes', wilayaId: 36 },{ name: 'Bougous', wilayaId: 36 },{ name: 'Bouhadjar', wilayaId: 36 },
  { name: 'Bouteldja', wilayaId: 36 },{ name: 'Chebaita Mokhtar', wilayaId: 36 },
  { name: 'Chefia', wilayaId: 36 },{ name: 'Chihani', wilayaId: 36 },{ name: 'Drean', wilayaId: 36 },
  { name: 'Echatt', wilayaId: 36 },{ name: 'El Aioun', wilayaId: 36 },{ name: 'El Kala', wilayaId: 36 },
  { name: 'El Tarf', wilayaId: 36 },{ name: 'Hammam Beni Salah', wilayaId: 36 },
  { name: 'Lac des Oiseaux', wilayaId: 36 },{ name: 'Oued Zitoun', wilayaId: 36 },
  { name: 'Raml Souk', wilayaId: 36 },{ name: 'Souarekh', wilayaId: 36 },{ name: 'Zerizer', wilayaId: 36 },
  { name: 'Zitouna', wilayaId: 36 },{ name: 'Oum el Assel', wilayaId: 37 },{ name: 'Tindouf', wilayaId: 37 },
  { name: 'Ammari', wilayaId: 38 },{ name: 'Beni Chaib', wilayaId: 38 },{ name: 'Beni Lahcene', wilayaId: 38 },
  { name: 'Boucaid', wilayaId: 38 },{ name: 'Bordj Bou Naama', wilayaId: 38 },
  { name: 'Bordj El Emir Abdelkader', wilayaId: 38 },{ name: 'Khemisti', wilayaId: 38 },
  { name: 'Larbaa', wilayaId: 38 },{ name: 'Lardjem', wilayaId: 38 },{ name: 'Layoune', wilayaId: 38 },
  { name: 'Lazharia', wilayaId: 38 },{ name: 'Maacem', wilayaId: 38 },{ name: 'Melaab', wilayaId: 38 },
  { name: 'Ouled Bessem', wilayaId: 38 },{ name: 'Sidi Abed', wilayaId: 38 },
  { name: 'Sidi Boutouchent', wilayaId: 38 },{ name: 'Sidi Lantri', wilayaId: 38 },
  { name: 'Sidi Slimane', wilayaId: 38 },{ name: 'Tamalaht', wilayaId: 38 },
  { name: 'Theniet El Had', wilayaId: 38 },{ name: 'Tissemsilt', wilayaId: 38 },
  { name: 'Youssoufia', wilayaId: 38 },{ name: 'El Oued', wilayaId: 39 },{ name: 'Robbah', wilayaId: 39 },
  { name: 'Oued El Alenda', wilayaId: 39 },{ name: 'Bayadha', wilayaId: 39 },{ name: 'Nakhla', wilayaId: 39 },
  { name: 'Guemar', wilayaId: 39 },{ name: 'Kouinine', wilayaId: 39 },{ name: 'Reguiba', wilayaId: 39 },
  { name: 'Hamraia', wilayaId: 39 },{ name: 'Taghzout', wilayaId: 39 },{ name: 'Debila', wilayaId: 39 },
  { name: 'Hassani Abdelkrim', wilayaId: 39 },{ name: 'Hassi Khalifa', wilayaId: 39 },
  { name: 'Taleb Larbi', wilayaId: 39 },{ name: 'Douar El Ma', wilayaId: 39 },{ name: 'Sidi Aoun', wilayaId: 39 },
  { name: 'Trifaoui', wilayaId: 39 },{ name: 'Magrane', wilayaId: 39 },{ name: 'Beni Guecha', wilayaId: 39 },
  { name: 'Ourmas', wilayaId: 39 },{ name: 'El Ogla', wilayaId: 39 },{ name: 'Mih Ouansa', wilayaId: 39 },
  { name: 'Ain Touila', wilayaId: 40 },{ name: 'Babar', wilayaId: 40 },{ name: 'Baghai', wilayaId: 40 },
  { name: 'Bouhmama', wilayaId: 40 },{ name: 'Chechar', wilayaId: 40 },{ name: 'Chelia', wilayaId: 40 },
  { name: 'Djellal', wilayaId: 40 },{ name: 'El Hamma', wilayaId: 40 },{ name: 'El Mahmal', wilayaId: 40 },
  { name: 'El Oueldja', wilayaId: 40 },{ name: 'Ensigha', wilayaId: 40 },{ name: 'Kais', wilayaId: 40 },
  { name: 'Khenchela', wilayaId: 40 },{ name: 'Khirane', wilayaId: 40 },{ name: "M'Sara", wilayaId: 40 },
  { name: "M'Toussa", wilayaId: 40 },{ name: 'Ouled Rechache', wilayaId: 40 },{ name: 'Remila', wilayaId: 40 },
  { name: 'Tamza', wilayaId: 40 },{ name: 'Taouzient', wilayaId: 40 },{ name: 'Yabous', wilayaId: 40 },
  { name: 'Souk Ahras', wilayaId: 41 },{ name: 'Sedrata', wilayaId: 41 },{ name: 'Hanancha', wilayaId: 41 },
  { name: 'Mechroha', wilayaId: 41 },{ name: 'Ouled Driss', wilayaId: 41 },{ name: 'Tiffech', wilayaId: 41 },
  { name: 'Zaarouria', wilayaId: 41 },{ name: 'Taoura', wilayaId: 41 },{ name: 'Drea', wilayaId: 41 },
  { name: 'Heddada', wilayaId: 41 },{ name: 'Khedara', wilayaId: 41 },{ name: 'Merahna', wilayaId: 41 },
  { name: 'Ouled Moumene', wilayaId: 41 },{ name: 'Bir Bou Haouch', wilayaId: 41 },
  { name: "M'daourouch", wilayaId: 41 },{ name: 'Oum El Adhaim', wilayaId: 41 },
  { name: 'Ain Zana', wilayaId: 41 },{ name: 'Ain Soltane', wilayaId: 41 },{ name: 'Ouillen', wilayaId: 41 },
  { name: 'Sidi Fredj', wilayaId: 41 },{ name: 'Safel El Ouiden', wilayaId: 41 },{ name: 'Ragouba', wilayaId: 41 },
  { name: 'Khemissa', wilayaId: 41 },{ name: 'Oued Keberit', wilayaId: 41 },{ name: 'Terraguelt', wilayaId: 41 },
  { name: 'Zouabi', wilayaId: 41 },{ name: 'Tipaza', wilayaId: 42 },{ name: 'Menaceur', wilayaId: 42 },
  { name: 'Larhat', wilayaId: 42 },{ name: 'Douaouda', wilayaId: 42 },{ name: 'Bourkika', wilayaId: 42 },
  { name: 'Khemisti', wilayaId: 42 },{ name: 'Aghbal', wilayaId: 42 },{ name: 'Hadjout', wilayaId: 42 },
  { name: 'Sidi Amar', wilayaId: 42 },{ name: 'Gouraya', wilayaId: 42 },{ name: 'Nador', wilayaId: 42 },
  { name: 'Chaiba', wilayaId: 42 },{ name: 'Ain Tagourait', wilayaId: 42 },{ name: 'Cherchell', wilayaId: 42 },
  { name: 'Damous', wilayaId: 42 },{ name: 'Merad', wilayaId: 42 },{ name: 'Fouka', wilayaId: 42 },
  { name: 'Bou Ismail', wilayaId: 42 },{ name: 'Ahmar El Ain', wilayaId: 42 },
  { name: 'Bouharoun', wilayaId: 42 },{ name: 'Sidi Ghiles', wilayaId: 42 },
  { name: 'Messelmoun', wilayaId: 42 },{ name: 'Sidi Rached', wilayaId: 42 },{ name: 'Kolea', wilayaId: 42 },
  { name: 'Attatba', wilayaId: 42 },{ name: 'Sidi Semiane', wilayaId: 42 },{ name: 'Beni Milleuk', wilayaId: 42 },
  { name: 'Hadjeret Ennous', wilayaId: 42 },{ name: 'Ahmed Rachedi', wilayaId: 43 },
  { name: 'Ain Beida Harriche', wilayaId: 43 },{ name: 'Ain Mellouk', wilayaId: 43 },
  { name: 'Ain Tine', wilayaId: 43 },{ name: 'Amira Arres', wilayaId: 43 },
  { name: 'Benyahia Abderrahmane', wilayaId: 43 },{ name: 'Bouhatem', wilayaId: 43 },
  { name: 'Chelghoum Laid', wilayaId: 43 },{ name: 'Chigara', wilayaId: 43 },
  { name: 'Derradji Bousselah', wilayaId: 43 },{ name: 'El Mechira', wilayaId: 43 },
  { name: 'Elayadi Barbes', wilayaId: 43 },{ name: 'Ferdjioua', wilayaId: 43 },
  { name: 'Grarem Gouga', wilayaId: 43 },{ name: 'Hamala', wilayaId: 43 },{ name: 'Mila', wilayaId: 43 },
  { name: 'Minar Zarza', wilayaId: 43 },{ name: 'Oued Athmania', wilayaId: 43 },
  { name: 'Oued Endja', wilayaId: 43 },{ name: 'Oued Seguen', wilayaId: 43 },
  { name: 'Ouled Khalouf', wilayaId: 43 },{ name: 'Rouached', wilayaId: 43 },
  { name: 'Sidi Khelifa', wilayaId: 43 },{ name: 'Sidi Merouane', wilayaId: 43 },
  { name: 'Tadjenanet', wilayaId: 43 },{ name: 'Tassadane Haddada', wilayaId: 43 },
  { name: 'Teleghma', wilayaId: 43 },{ name: 'Terrai Bainen', wilayaId: 43 },
  { name: 'Tessala Lemtai', wilayaId: 43 },{ name: 'Tiberguent', wilayaId: 43 },
  { name: 'Yahia Beni Guecha', wilayaId: 43 },{ name: 'Zeghaia', wilayaId: 43 },
  { name: 'Ain Benian', wilayaId: 44 },{ name: 'Ain Bouyahia', wilayaId: 44 },
  { name: 'Ain Defla', wilayaId: 44 },{ name: 'Ain Lechiakh', wilayaId: 44 },
  { name: 'Ain Soltane', wilayaId: 44 },{ name: 'Ain Torki', wilayaId: 44 },{ name: 'Bathia', wilayaId: 44 },
  { name: 'Belaas', wilayaId: 44 },{ name: 'Ben Allal', wilayaId: 44 },
  { name: 'Bir Ouled Khelifa', wilayaId: 44 },{ name: 'Bordj Emir Khaled', wilayaId: 44 },
  { name: 'Boumedfaa', wilayaId: 44 },{ name: 'Bourached', wilayaId: 44 },{ name: 'Djelida', wilayaId: 44 },
  { name: 'Djemaa Ouled Cheikh', wilayaId: 44 },{ name: 'El Abadia', wilayaId: 44 },
  { name: 'El Amra', wilayaId: 44 },{ name: 'El Attaf', wilayaId: 44 },{ name: 'El Hassania', wilayaId: 44 },
  { name: 'El Maine', wilayaId: 44 },{ name: 'Hammam Righa', wilayaId: 44 },{ name: 'Hoceinia', wilayaId: 44 },
  { name: 'Khemis Miliana', wilayaId: 44 },{ name: 'Mekhatria', wilayaId: 44 },{ name: 'Miliana', wilayaId: 44 },
  { name: 'Oued Chorfa', wilayaId: 44 },{ name: 'Oued Djemaa', wilayaId: 44 },{ name: 'Rouina', wilayaId: 44 },
  { name: 'Sidi Lakhdar', wilayaId: 44 },{ name: 'Tachi Zegagha', wilayaId: 44 },
  { name: 'Tarik Ibn Ziad', wilayaId: 44 },{ name: 'Tiberkanine', wilayaId: 44 },
  { name: 'Zeddine', wilayaId: 44 },{ name: 'Naama', wilayaId: 45 },{ name: 'Mecheria', wilayaId: 45 },
  { name: 'Ain Sefra', wilayaId: 45 },{ name: 'Tiout', wilayaId: 45 },{ name: 'Sfissifa', wilayaId: 45 },
  { name: 'Moghrar', wilayaId: 45 },{ name: 'Assela', wilayaId: 45 },{ name: 'Djeniene Bourezg', wilayaId: 45 },
  { name: 'Makman Ben Amer', wilayaId: 45 },{ name: 'Kasdir', wilayaId: 45 },{ name: 'El Biod', wilayaId: 45 },
  { name: 'Aghlal', wilayaId: 46 },{ name: 'Ain El Arbaa', wilayaId: 46 },{ name: 'Ain Kihal', wilayaId: 46 },
  { name: 'Ain Temouchent', wilayaId: 46 },{ name: 'Ain Tolba', wilayaId: 46 },
  { name: 'Aoubellil', wilayaId: 46 },{ name: 'Beni Saf', wilayaId: 46 },{ name: 'Bouzedjar', wilayaId: 46 },
  { name: 'Chaabat El Leham', wilayaId: 46 },{ name: 'Chentouf', wilayaId: 46 },
  { name: 'El Amria', wilayaId: 46 },{ name: 'El Emir Abdelkader', wilayaId: 46 },
  { name: 'El Malah', wilayaId: 46 },{ name: 'El Messaid', wilayaId: 46 },
  { name: 'Hammam Bouhadjar', wilayaId: 46 },{ name: 'Hassasna', wilayaId: 46 },
  { name: 'Hassi El Ghella', wilayaId: 46 },{ name: 'Oued Berkeche', wilayaId: 46 },
  { name: 'Oued Sabah', wilayaId: 46 },{ name: 'Ouled Boudjemaa', wilayaId: 46 },
  { name: 'Ouled Kihal', wilayaId: 46 },{ name: 'Oulhaca El Gheraba', wilayaId: 46 },
  { name: 'Sidi Ben Adda', wilayaId: 46 },{ name: 'Sidi Boumedienne', wilayaId: 46 },
  { name: 'Sidi Ouriache', wilayaId: 46 },{ name: 'Sidi Safi', wilayaId: 46 },{ name: 'Tamzoura', wilayaId: 46 },
  { name: 'Terga', wilayaId: 46 },{ name: 'Berriane', wilayaId: 47 },{ name: 'Bounoura', wilayaId: 47 },
  { name: 'Dhayet Bendhahoua', wilayaId: 47 },{ name: 'El Atteuf', wilayaId: 47 },
  { name: 'El Guerrara', wilayaId: 47 },{ name: 'Ghardaia', wilayaId: 47 },{ name: 'Mansoura', wilayaId: 47 },
  { name: 'Metlili', wilayaId: 47 },{ name: 'Sebseb', wilayaId: 47 },{ name: 'Zelfana', wilayaId: 47 },
  { name: 'Ain Rahma', wilayaId: 48 },{ name: 'Ain Tarek', wilayaId: 48 },{ name: 'Ammi Moussa', wilayaId: 48 },
  { name: 'Belassel Bouzegza', wilayaId: 48 },{ name: 'Bendaoud', wilayaId: 48 },
  { name: 'Beni Dergoun', wilayaId: 48 },{ name: 'Beni Zentis', wilayaId: 48 },
  { name: 'Dar Ben Abdellah', wilayaId: 48 },{ name: 'Djidioua', wilayaId: 48 },
  { name: 'El Guettar', wilayaId: 48 },{ name: 'El Hamadna', wilayaId: 48 },{ name: 'El Hassi', wilayaId: 48 },
  { name: 'El Matmar', wilayaId: 48 },{ name: 'El Ouldja', wilayaId: 48 },{ name: 'Had Echkalla', wilayaId: 48 },
  { name: 'Hamri', wilayaId: 48 },{ name: 'Kalaa', wilayaId: 48 },{ name: 'Lahlef', wilayaId: 48 },
  { name: 'Mazouna', wilayaId: 48 },{ name: 'Mediouna', wilayaId: 48 },{ name: 'Mendes', wilayaId: 48 },
  { name: 'Merdja Sidi Abed', wilayaId: 48 },{ name: 'Ouarizane', wilayaId: 48 },
  { name: 'Oued Essalem', wilayaId: 48 },{ name: 'Oued Rhiou', wilayaId: 48 },
  { name: 'Ouled Aiche', wilayaId: 48 },{ name: 'Ouled Sidi Mihoub', wilayaId: 48 },
  { name: 'Ramka', wilayaId: 48 },{ name: 'Relizane', wilayaId: 48 },{ name: 'Sidi Khettab', wilayaId: 48 },
  { name: 'Sidi Lazreg', wilayaId: 48 },{ name: "Sidi M'Hamed Ben Ali", wilayaId: 48 },
  { name: "Sidi M'Hamed Benaouda", wilayaId: 48 },{ name: 'Sidi Saada', wilayaId: 48 },
  { name: 'Souk El Had', wilayaId: 48 },{ name: 'Yellel', wilayaId: 48 },{ name: 'Zemmora', wilayaId: 48 },
  { name: 'Aougrout', wilayaId: 49 },{ name: 'Charouine', wilayaId: 49 },{ name: 'Deldoul', wilayaId: 49 },
  { name: 'Ksar Kaddour', wilayaId: 49 },{ name: 'Metarfa', wilayaId: 49 },
  { name: 'Ouled Aissa', wilayaId: 49 },{ name: 'Ouled Said', wilayaId: 49 },{ name: 'Talmine', wilayaId: 49 },
  { name: 'Timimoun', wilayaId: 49 },{ name: 'Tinerkouk', wilayaId: 49 },
  { name: 'Bordj Badji Mokhtar', wilayaId: 50 },{ name: 'Timiaouine', wilayaId: 50 },
  { name: 'Besbes', wilayaId: 51 },{ name: 'Ech Chaiba', wilayaId: 51 },{ name: 'Doucen', wilayaId: 51 },
  { name: 'Ouled Djellal', wilayaId: 51 },{ name: 'Sidi Khaled', wilayaId: 51 },
  { name: 'Ras El Miaad', wilayaId: 51 },{ name: 'Beni Abbes', wilayaId: 52 },
  { name: 'Ouled Khodeir', wilayaId: 52 },{ name: 'Timoudi', wilayaId: 52 },
  { name: 'Beni Ikhlef', wilayaId: 52 },{ name: 'Igli', wilayaId: 52 },{ name: 'Tabelbala', wilayaId: 52 },
  { name: 'El Ouata', wilayaId: 52 },{ name: 'Kerzaz', wilayaId: 52 },{ name: 'Ksabi', wilayaId: 52 },
  { name: 'Tamtert', wilayaId: 52 },{ name: 'In Salah', wilayaId: 53 },
  { name: 'Foggaret Ezzaouia', wilayaId: 53 },{ name: 'In Ghar', wilayaId: 53 },
  { name: 'In Guezzam', wilayaId: 54 },{ name: 'Tin Zaouatine', wilayaId: 54 },
  { name: 'Benaceur', wilayaId: 55 },{ name: 'Blidet Amor', wilayaId: 55 },{ name: 'El Allia', wilayaId: 55 },
  { name: 'El Hadjira', wilayaId: 55 },{ name: 'Megarine', wilayaId: 55 },{ name: "M'Naguer", wilayaId: 55 },
  { name: 'Nezla', wilayaId: 55 },{ name: 'Sidi Slimane', wilayaId: 55 },{ name: 'Taibet', wilayaId: 55 },
  { name: 'Temacine', wilayaId: 55 },{ name: 'Tebesbest', wilayaId: 55 },{ name: 'Touggourt', wilayaId: 55 },
  { name: 'Zaouia El Abidia', wilayaId: 55 },{ name: 'Djanet', wilayaId: 56 },
  { name: 'Bordj El Haouas', wilayaId: 56 },{ name: 'Djamaa', wilayaId: 57 },{ name: "El M'Ghair", wilayaId: 57 },
  { name: 'Merara', wilayaId: 57 },{ name: 'Oum Touyour', wilayaId: 57 },{ name: 'Sidi Amrane', wilayaId: 57 },
  { name: 'Sidi Khellil', wilayaId: 57 },{ name: 'Still', wilayaId: 57 },{ name: 'Tendla', wilayaId: 57 },
  { name: 'El Menia', wilayaId: 58 },{ name: 'Hassi Gara', wilayaId: 58 },{ name: 'Hassi Fehal', wilayaId: 58 },
];

const PRODUCTS = [
  {
    name: 'Smartphone Galaxy S24', price: 249900, oldPrice: 289900,
    color: "#000000", sku: 'SAM-S24-256',
    images: ['https://placehold.co/400x400/cb11ab/white?text=S24', 'https://placehold.co/400x400/481173/white?text=S24+2', 'https://placehold.co/400x400/222/white?text=S24+3', 'https://placehold.co/400x400/cb11ab/white?text=S24+4', 'https://placehold.co/400x400/333/white?text=S24+5'],
    description: 'Smartphone Samsung 256Go, écran 6.8", appareil 200MP - Livraison rapide'
  },
  {
    name: 'iPhone 16 Pro Max', price: 289900, oldPrice: 329900,
    color: "#1a365d", sku: 'APP-IP16PM-256',
    images: ['https://placehold.co/400x400/481173/white?text=iPhone16', 'https://placehold.co/400x400/cb11ab/white?text=iPhone+2', 'https://placehold.co/400x400/222/white?text=iPhone+3', 'https://placehold.co/400x400/481173/white?text=iPhone+4', 'https://placehold.co/400x400/333/white?text=iPhone+5'],
    description: 'Apple iPhone 16 Pro Max 256Go, titane, caméra 48MP'
  },
  {
    name: 'AirPods Pro 2', price: 49900, oldPrice: 59900,
    color: "#7c3aed", sku: 'APP-AIRP2-USB',
    images: ['https://placehold.co/400x400/cb11ab/white?text=AirPods', 'https://placehold.co/400x400/481173/white?text=AirPods+2', 'https://placehold.co/400x400/222/white?text=AirPods+3', 'https://placehold.co/400x400/cb11ab/white?text=AirPods+4', 'https://placehold.co/400x400/333/white?text=AirPods+5'],
    description: 'AirPods Pro 2 USB-C, réduction de bruit active'
  },
  {
    name: 'Chaussures Nike Air Max', price: 49900, oldPrice: 59900,
    color: "#dc2626", sku: 'NIK-AIRMX-270',
    images: ['https://placehold.co/400x400/481173/white?text=Nike', 'https://placehold.co/400x400/cb11ab/white?text=Nike+2', 'https://placehold.co/400x400/222/white?text=Nike+3', 'https://placehold.co/400x400/333/white?text=Nike+4', 'https://placehold.co/400x400/481173/white?text=Nike+5'],
    description: 'Nike Air Max 270, confort et style'
  },
  {
    name: 'Parfum Chanel N°5', price: 54900, oldPrice: 64900,
    color: "#059669", sku: 'CHAN-N5-50ML',
    images: ['https://placehold.co/400x400/cb11ab/white?text=Chanel5', 'https://placehold.co/400x400/481173/white?text=Chanel+2', 'https://placehold.co/400x400/222/white?text=Chanel+3', 'https://placehold.co/400x400/333/white?text=Chanel+4', 'https://placehold.co/400x400/cb11ab/white?text=Chanel+5'],
    description: 'Parfum Chanel N°5, 50ml, élégance française'
  },
  {
    name: 'Casque Sony WH-1000XM5', price: 99900, oldPrice: 119900,
    color: "#2563eb", sku: 'SON-WHXM5-BLK',
    images: ['https://placehold.co/400x400/481173/white?text=SonyXM5', 'https://placehold.co/400x400/cb11ab/white?text=Sony+2', 'https://placehold.co/400x400/222/white?text=Sony+3', 'https://placehold.co/400x400/cb11ab/white?text=Sony+4', 'https://placehold.co/400x400/333/white?text=Sony+5'],
    description: 'Casque sans fil Sony, réduction de bruit adaptative'
  },
  {
    name: 'Sac à main Dior', price: 149900, oldPrice: null,
    color: "#d97706", sku: 'DIOR-BAG-LTR',
    images: ['https://placehold.co/400x400/cb11ab/white?text=Dior', 'https://placehold.co/400x400/481173/white?text=Dior+2', 'https://placehold.co/400x400/222/white?text=Dior+3', 'https://placehold.co/400x400/333/white?text=Dior+4', 'https://placehold.co/400x400/cb11ab/white?text=Dior+5'],
    description: 'Sac à main Dior femme, cuir de qualité'
  },
  {
    name: 'Montre connectée Galaxy Watch', price: 89900, oldPrice: 109900,
    color: "#be185d", sku: 'SAM-GW6C-44',
    images: ['https://placehold.co/400x400/481173/white?text=Watch6', 'https://placehold.co/400x400/cb11ab/white?text=Watch+2', 'https://placehold.co/400x400/222/white?text=Watch+3', 'https://placehold.co/400x400/333/white?text=Watch+4', 'https://placehold.co/400x400/481173/white?text=Watch+5'],
    description: 'Samsung Galaxy Watch 6 Classic, santé et fitness'
  },
  {
    name: 'T-shirt Nike Sportswear', price: 5900, oldPrice: 7900,
    color: "#000000", sku: 'NIK-TS-BLK',
    images: ['https://placehold.co/400x400/cb11ab/white?text=TSHIRT', 'https://placehold.co/400x400/481173/white?text=TSHIRT+2', 'https://placehold.co/400x400/222/white?text=TSHIRT+3', 'https://placehold.co/400x400/cb11ab/white?text=TSHIRT+4', 'https://placehold.co/400x400/333/white?text=TSHIRT+5'],
    description: 'T-shirt Nike Dri-FIT, confort et style sportif',
    tierEnabled: true, tierQty: 3, tierPrice: 4900,
    tierMessage: '➕ أضف {remaining} فقط ووفر 1000 د.ج لكل قطعة!',
    tierGift: '⭐ Autocollant Nike gratuit'
  },
  {
    name: 'Enceinte JBL Flip 6', price: 29900, oldPrice: null,
    color: "#4f46e5", sku: 'JBL-FLP6-BLU',
    images: ['https://placehold.co/400x400/481173/white?text=JBL', 'https://placehold.co/400x400/cb11ab/white?text=JBL+2', 'https://placehold.co/400x400/222/white?text=JBL+3', 'https://placehold.co/400x400/333/white?text=JBL+4', 'https://placehold.co/400x400/481173/white?text=JBL+5'],
    description: 'Enceinte Bluetooth portable JBL Flip 6, son puissant'
  },
];

async function main() {
  const existing = await prisma.product.count();
  if (existing > 0) {
    console.log('✅ Database already seeded — skipping');
    await prisma.$disconnect();
    process.exit(0);
  }

  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.commune.deleteMany();
  await prisma.wilaya.deleteMany();

  for (const w of WILAYAS) await prisma.wilaya.create({ data: w });
  for (const c of COMMUNES) await prisma.commune.create({ data: c });

  for (let i = 0; i < PRODUCTS.length; i++) {
    const p = PRODUCTS[i];
    await prisma.product.create({
      data: {
        slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + i,
        name: p.name,
        price: p.price,
        oldPrice: p.oldPrice,
        color: p.color || '#000000',
        sku: p.sku,
        images: JSON.stringify(p.images),
        description: p.description,
        stock: Math.floor(Math.random() * 20) + 2,
        tierEnabled: p.tierEnabled || false,
        tierQty: p.tierQty || null,
        tierPrice: p.tierPrice || null,
        tierMessage: p.tierMessage || null,
        tierGift: p.tierGift || null,
      },
    });
  }

  console.log(`✅ ${PRODUCTS.length} produits | ${WILAYAS.length} wilayas | ${COMMUNES.length} communes`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
