import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

function cat(c) {
  const map = {
    'algerie': 'الجزائر / القصبة',
    'art': 'فن ورسم',
    'couple': 'ثنائي',
    'cuisine': 'مطبخ',
    'enfants': 'أطفال',
    'islamique': 'إسلامي / عربي',
    'medical': 'طبي',
    'paysage': 'طبيعة وورود',
    'pack6': 'باقة 6 لوحات',
    'duo': 'ثنائي',
    'trio-duo': 'ثلاثي وثنائي',
    'abstrait': 'تجريدي',
    'orva': 'orva',
  };
  return map[c] || c;
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim()
    .substring(0, 80) || 'product';
}

function arabicName(fr) {
  return fr;
}

let pid = 2000;

function nextPos() {
  return pid++;
}

const algerieProducts = [];
for (let i = 1; i <= 30; i++) {
  const name = `Dzair ${i}`;
  algerieProducts.push({
    name: `الجزائر ${i}`,
    slug: `dzair-${i}`,
    price: i === 7 ? 3000 : 2500,
    images: '[]',
    description: `لوحة Dzair ${i} - خريطة الجزائر بريشة فنية جميلة. مطبوعة على قماش كانفاس عالي الجودة.`,
    color: '#a10510',
    category: cat('algerie'),
    sku: `ORVA-DZAIR-${String(i).padStart(2, '0')}`,
    stock: 10,
    active: true,
    position: nextPos(),
  });
}

const products = [
  ...algerieProducts,

  {
    name: 'باقة الجزائر',
    slug: 'pack-algerie',
    price: 5500,
    images: '[]',
    description: 'باقة من اللوحات الجزائرية المتنوعة. مجموعة رائعة من تصاميم Dzair.',
    color: '#a10510',
    category: cat('algerie'),
    sku: 'ORVA-PACK-DZ',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'باقة القصبة',
    slug: 'pack-casbah',
    price: 5500,
    images: '[]',
    description: 'باقة من لوحات القصبة الجزائرية. مزيج من التراث والجمال.',
    color: '#a10510',
    category: cat('algerie'),
    sku: 'ORVA-PACK-CASBAH',
    stock: 5,
    active: true,
    position: nextPos(),
  },

  // ART & PEINTURE
  {
    name: 'Abstrait à texture sablée beige',
    slug: 'abstrait-texture-sablee-beige',
    price: 3000,
    images: '[]',
    description: 'لوحة تجريدية بنسيج رملي بيج. إضافة راقية لديكور منزلك.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'The Brush Nude',
    slug: 'the-brush-nude',
    price: 3900,
    images: '[]',
    description: 'لوحة فنية عصرية بلمسات فرشاة عارية. تصميم أنيق وحديث.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Matisse coloré',
    slug: 'matisse-colore',
    price: 4600,
    images: '[]',
    description: 'لوحة مستوحاة من أسلوب ماتيس الفني بألوان زاهية ومبهجة.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Douceur Rosée abstrait vert gris rose',
    slug: 'douceur-rose-abstrait',
    price: 6400,
    images: '[]',
    description: 'لوحة تجريدية ناعمة بألوان الزهري والرمادي والأخضر. لمسة من الأنوثة والرقة.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Jardin floral',
    slug: 'jardin-floral',
    price: 4600,
    images: '[]',
    description: 'لوحة حديقة زهرية جميلة تضفي الحياة والبهجة على أي جدار.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Forêt Dorée grise',
    slug: 'foret-doree-grise',
    price: 4500,
    images: '[]',
    description: 'غابة ذهبية رمادية بتصميم فني ساحر. مزيج من الذهبي والرمادي.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Horizon beige abstrait',
    slug: 'horizon-beige-abstrait-2',
    price: 3000,
    images: '[]',
    description: 'أفق بيج تجريدي - لوحة عصرية هادئة مثالية لغرفة المعيشة أو غرفة النوم. طبعة فاخرة على قماش.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'The Van Gogh Art',
    slug: 'van-gogh-art',
    price: 4600,
    images: '[]',
    description: 'لوحة مستوحاة من فن فان جوخ. تحفة فنية كلاسيكية عصرية.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-ART-008',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs Bleu',
    slug: 'fleurs-bleu',
    price: 5800,
    images: '[]',
    description: 'لوحة زهور زرقاء كبيرة الحجم. تصميم راقي بألوان زرقاء ساحرة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-FL-BLEU',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Plume Bleu',
    slug: 'plume-bleu',
    price: 5800,
    images: '[]',
    description: 'لوحة ريشة زرقاء أنيقة. تصميم عصري وناعم.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-PLUME-BLEU',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs Grise & doré',
    slug: 'fleurs-grise-dore',
    price: 4600,
    images: '[]',
    description: 'لوحة زهور بالرمادي والذهبي. مزيج فاخر من الألوان.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-FL-GRISE',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Matisse Beige Marron',
    slug: 'matisse-beige-marron',
    price: 3900,
    images: '[]',
    description: 'لوحة ماتيس بألوان البيج والبنّي. تصميم دافئ وأنيق.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-MATISSE-BM',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Art contemporain Beige & noir',
    slug: 'art-contemporain-beige-noir',
    price: 3900,
    images: '[]',
    description: 'لوحة فن معاصر بالأبيض والأسود والبيج. تصميم عصري أنيق.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-CONTEMP-BN',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Modèle Claude Monet',
    slug: 'claude-monet-modele',
    price: 4600,
    images: '[]',
    description: 'لوحة مستوحاة من الفنان كلود مونيه. لمسة من الانطباعية الفرنسية.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-MONET',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Poussiere Beige Gold',
    slug: 'poussiere-beige-gold',
    price: 4800,
    images: '[]',
    description: 'لوحة بوسيير بيج وذهبي. تصميم فاخر بألوان ذهبية.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-PBG',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Painting abstract black & beige',
    slug: 'painting-abstract-black-beige',
    price: 3000,
    images: '[]',
    description: 'لوحة تجريدية بالأبيض والأسود والبيج. تصميم بسيط وأنيق.',
    color: '#a10510',
    category: cat('abstrait'),
    sku: 'ORVA-ABSTRACT-BB',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait grey & gold',
    slug: 'abstrait-grey-gold',
    price: 3000,
    images: '[]',
    description: 'لوحة تجريدية بالرمادي والذهبي. لمسة عصرية فاخرة.',
    color: '#a10510',
    category: cat('abstrait'),
    sku: 'ORVA-ABSTRACT-GG',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Couleurs de vie',
    slug: 'couleurs-de-vie',
    price: 3000,
    images: '[]',
    description: 'لوحة ألوان الحياة - تصميم زاهي ومليء بالطاقة.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-CDV',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'William Morris',
    slug: 'william-morris',
    price: 1600,
    images: '[]',
    description: 'لوحة وليام موريس - تصميم كلاسيكي مستوحى من فنون الطبيعة.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-MORRIS',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Henri Matisse Joy of Smiles',
    slug: 'henri-matisse-joy-of-smiles',
    price: 2500,
    images: '[]',
    description: 'لوحة هنري ماتيس - فرحة الابتسامات. تصميم مليء بالبهجة.',
    color: '#a10510',
    category: cat('art'),
    sku: 'ORVA-MATISSE-JOY',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait au trait beige noir',
    slug: 'abstrait-trait-beige-noir',
    price: 3000,
    images: '[]',
    description: 'لوحة تجريدية بخطوط بيج وسوداء. تصميم minimalist أنيق.',
    color: '#a10510',
    category: cat('abstrait'),
    sku: 'ORVA-ABSTRACT-TBN',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // COUPLE
  {
    name: 'Couple line en rose',
    slug: 'couple-line-rose',
    price: 4600,
    images: '[]',
    description: 'لوحة ثنائي بخطوط وردية. تصميم رومانسي للحبيبين.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Couple line beige',
    slug: 'couple-line-beige',
    price: 4600,
    images: '[]',
    description: 'لوحة ثنائي بخطوط بيج. تصميم أنيق وناعم للحبيبين.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Couple All of me loves all of you',
    slug: 'couple-all-of-me',
    price: 4600,
    images: '[]',
    description: 'لوحة ثنائي رومانسية - كل ما فيّ يحب كل ما فيك. هدية مثالية.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Trio All of me loves all of you',
    slug: 'trio-all-of-me',
    price: 4600,
    images: '[]',
    description: 'لوحة ثلاثية رومانسية - كل ما فيّ يحب كل ما فيك. ثلاث لوحات متناسقة.',
    color: '#a10510',
    category: cat('trio-duo'),
    sku: 'ORVA-CPL-TRIO',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Couple مودة و رحمة',
    slug: 'couple-mawadda-wa-rahma',
    price: 3900,
    images: '[]',
    description: 'لوحة ثنائي - مودة ورحمة. تصميم إسلامي رومانسي.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'His only Her only',
    slug: 'his-only-her-only',
    price: 4600,
    images: '[]',
    description: 'لوحة His Only Her Only - تصميم رومانسي للحبيبين.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Family',
    slug: 'family-couple',
    price: 4600,
    images: '[]',
    description: 'لوحة عائلة - تصميم دافئ يعبر عن الأسرة والترابط.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-FAM',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Sabr Houb Shukr Beige',
    slug: 'sabr-houb-shukr-beige',
    price: 4600,
    images: '[]',
    description: 'لوحة صبر حب شكر - تصميم بيج أنيق بكلمات مؤثرة.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-SHR-BG',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'وجعل بينكم مودة ورحمة COUPLE ROSE',
    slug: 'wajaala-baynakum-couple-rose',
    price: 3900,
    images: '[]',
    description: 'وجعل بينكم مودة ورحمة - لوحة ثنائي وردية رومانسية.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-CPL-ROSE',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Yours & Mine',
    slug: 'yours-and-mine',
    price: 2800,
    images: '[]',
    description: 'لوحة Yours & Mine - لك ولي. تصميم رومانسي جميل.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-YM',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'All of me loves all of you Floral',
    slug: 'all-of-me-floral',
    price: 3200,
    images: '[]',
    description: 'لوحة All of me loves all of you - تصميم زهري رومانسي.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-AM-FLORAL',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Love & Patience',
    slug: 'love-and-patience',
    price: 3200,
    images: '[]',
    description: 'لوحة Love & Patience - حب وصبر. تصميم راقي.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-LP',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Sabr Houb Beige',
    slug: 'sabr-houb-beige',
    price: 4600,
    images: '[]',
    description: 'لوحة صبر حب بيج - تصميم ناعم بكلمات جميلة.',
    color: '#a10510',
    category: cat('couple'),
    sku: 'ORVA-SH-BEIGE',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // CUISINE
  {
    name: 'Cuisine bois botanique',
    slug: 'cuisine-bois-botanique',
    price: 1950,
    images: '[]',
    description: 'لوحة مطبخ بطابع خشبي نباتي. ديكور جميل للمطبخ.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cuisine Art line',
    slug: 'cuisine-art-line',
    price: 2400,
    images: '[]',
    description: 'لوحة مطبخ بتصميم خطوط فنية. عصرية وأنيقة.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cuisine moderne',
    slug: 'cuisine-moderne',
    price: 3000,
    images: '[]',
    description: 'لوحة مطبخ عصرية بتصميم حديث.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Modèle pour Cuisine',
    slug: 'modele-pour-cuisine',
    price: 650,
    images: '[]',
    description: 'موديل صغير للمطبخ. تصميم لطيف وبأسعار معقولة.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cooking is love',
    slug: 'cooking-is-love',
    price: 2500,
    images: '[]',
    description: 'لوحة الطبخ حب - تصميم جميل لعشاق الطبخ.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Café 1',
    slug: 'cafe-1',
    price: 1400,
    images: '[]',
    description: 'لوحة قهوة - تصميم جميل لمحبي القهوة.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cuisine bois botanique N°2',
    slug: 'cuisine-bois-botanique-2',
    price: 2400,
    images: '[]',
    description: 'لوحة مطبخ خشبية نباتية رقم 2. تصميم طبيعي جميل.',
    color: '#a10510',
    category: cat('cuisine'),
    sku: 'ORVA-CSN-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // ENFANTS
  {
    name: 'Pink Rainbow and Sun',
    slug: 'pink-rainbow-sun',
    price: 1500,
    images: '[]',
    description: 'لوحة أطفال قوس قزح وردي وشمس. تصميم مرح للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Rainbow islamique Rose',
    slug: 'rainbow-islamique-rose',
    price: 1500,
    images: '[]',
    description: 'قوس قزح إسلامي وردي - لوحة أطفال بتصميم إسلامي.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Astronaute beige',
    slug: 'astronaute-beige',
    price: 2800,
    images: '[]',
    description: 'لوحة رائد فضاء بيج - تصميم فضاء للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'أدعية التحصين للأطفال',
    slug: 'ad3iyat-tahseen-atfal',
    price: 1000,
    images: '[]',
    description: 'أدعية التحصين للأطفال - لوحة تعليمية دينية للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Petite fillette',
    slug: 'petite-fillette',
    price: 2000,
    images: '[]',
    description: 'لوحة طفلة صغيرة - تصميم لطيف للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Petite fille en rose',
    slug: 'petite-fille-rose',
    price: 2000,
    images: '[]',
    description: 'لوحة طفلة بالوردي - تصميم ناعم وجميل.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fille en Fleurs',
    slug: 'fille-en-fleurs',
    price: 1500,
    images: '[]',
    description: 'لوحة فتاة بين الزهور - تصميم جميل ورقيق.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cygne rose',
    slug: 'cygne-rose',
    price: 1500,
    images: '[]',
    description: 'لوحة بجعة وردية - تصميم أنيق للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-008',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Les règles de la chambre',
    slug: 'regles-chambre',
    price: 950,
    images: '[]',
    description: 'لوحة قواعد الغرفة - تصميم تعليمي ممتع للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-009',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Les règles de ma chambre',
    slug: 'regles-ma-chambre',
    price: 950,
    images: '[]',
    description: 'لوحة قواعد غرفتي - تصميم تعليمي ممتع للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-010',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Be Brave',
    slug: 'be-brave',
    price: 1500,
    images: '[]',
    description: 'لوحة كن شجاعاً - تصميم تحفيزي للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-011',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Lapin Nuage',
    slug: 'lapin-nuage',
    price: 1000,
    images: '[]',
    description: 'لوحة أرنب وسحاب - تصميم لطيف وناعم.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-012',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Spider Man',
    slug: 'spider-man',
    price: 2000,
    images: '[]',
    description: 'لوحة سبايدر مان - تصميم ممتع للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-013',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Yellow Trucks',
    slug: 'yellow-trucks',
    price: 3000,
    images: '[]',
    description: 'لوحة شاحنات صفراء - تصميم مرح للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-014',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ours Jaune',
    slug: 'ours-jaune',
    price: 1500,
    images: '[]',
    description: 'لوحة دب أصفر - تصميم لطيف للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-015',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Nursery Boho beige',
    slug: 'nursery-boho-beige',
    price: 1950,
    images: '[]',
    description: 'لوحة حضانة بوهو بيج - تصميم عصري لغرفة الأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-016',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Tableau Safari Toile',
    slug: 'safari-toile',
    price: 1600,
    images: '[]',
    description: 'لوحة سفاري على قماش - تصميم الحيوانات للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-017',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Animaux Rigolo',
    slug: 'animaux-rigolo',
    price: 3000,
    images: '[]',
    description: 'لوحة حيوانات مضحكة - تصميم مرح للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-018',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'My little princesse',
    slug: 'my-little-princess',
    price: 1500,
    images: '[]',
    description: 'لوحة أميرتي الصغيرة - تصميم رقيق للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-019',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Little princess fillette',
    slug: 'little-princess-fillette',
    price: 1500,
    images: '[]',
    description: 'لوحة أميرة صغيرة - تصميم جميل للبنات.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-020',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Lionceau nude',
    slug: 'lionceau-nude',
    price: 3600,
    images: '[]',
    description: 'لوحة شبل أسد بيج - تصميم فاخر للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-021',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Animaux safari',
    slug: 'animaux-safari',
    price: 2000,
    images: '[]',
    description: 'لوحة حيوانات سفاري - تصميم تعليمي للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-022',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Morning Dua',
    slug: 'morning-dua',
    price: 800,
    images: '[]',
    description: 'دعاء الصباح - لوحة دينية للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-023',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Night Dua',
    slug: 'night-dua',
    price: 800,
    images: '[]',
    description: 'دعاء المساء - لوحة دينية للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-024',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Rainbow Girly rose',
    slug: 'rainbow-girly-rose',
    price: 3900,
    images: '[]',
    description: 'قوس قزح بناتي وردي - لوحة كبيرة وجميلة.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-025',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Carte du monde enfant (World map kids)',
    slug: 'world-map-kids',
    price: 3000,
    images: '[]',
    description: 'خريطة العالم للأطفال - لوحة تعليمية ممتعة.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-026',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Lapinou rose',
    slug: 'lapinou-rose',
    price: 3900,
    images: '[]',
    description: 'لوحة أرنب وردي - تصميم لطيف وكبير.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-027',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Animaux Rigolos',
    slug: 'animaux-rigolos',
    price: 2400,
    images: '[]',
    description: 'لوحة حيوانات مضحكة - تصميم مرح.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-028',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Carte du monde',
    slug: 'carte-du-monde',
    price: 3000,
    images: '[]',
    description: 'خريطة العالم - لوحة تعليمية جميلة.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-029',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Gaming jeux vidéo colorée',
    slug: 'gaming-colorful',
    price: 3900,
    images: '[]',
    description: 'لوحة ألعاب فيديو ملونة - تصميم ممتاز لعشاق الألعاب.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-030',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Nounours Beige',
    slug: 'nounours-beige',
    price: 3900,
    images: '[]',
    description: 'لوحة دبدوب بيج - تصميم ناعم وجميل.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-031',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Papillons Rose',
    slug: 'papillons-rose',
    price: 3900,
    images: '[]',
    description: 'لوحة فراشات وردية - تصميم رقيق وأنيق.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-032',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Gaming jeux vidéo',
    slug: 'gaming-jeux-video',
    price: 2800,
    images: '[]',
    description: 'لوحة ألعاب فيديو - تصميم لعشاق الألعاب.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-033',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'سور و معوذات',
    slug: 'sour-wa-moawidat',
    price: 1300,
    images: '[]',
    description: 'سور ومعوذات - لوحة دينية للأطفال.',
    color: '#a10510',
    category: cat('enfants'),
    sku: 'ORVA-ENF-034',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // ISLAMIQUE / Arabesque
  {
    name: 'Doua floral ولسوف يعطيك ربك فترضى rose',
    slug: 'doua-floral-yardha-rose',
    price: 5500,
    images: '[]',
    description: 'دعاء فلورال - ولسوف يعطيك ربك فترضى. تصميم وردي راقي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique nuance de marron',
    slug: 'islamique-nuance-marron',
    price: 3900,
    images: '[]',
    description: 'لوحة إسلامية بدرجات البني - تصميم دافئ وأنيق.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Doua floral ألا بذكر الله تطمئن القلوب',
    slug: 'doua-bidhikrillah',
    price: 2500,
    images: '[]',
    description: 'دعاء فلورال - ألا بذكر الله تطمئن القلوب. تصميم زهري.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pampas islamique',
    slug: 'pampas-islamique',
    price: 4600,
    images: '[]',
    description: 'لوحة إسلامية بامباس - تصميم ناعم بطابع إسلامي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Arabic Quotes',
    slug: 'arabic-quotes',
    price: 3900,
    images: '[]',
    description: 'لوحة اقتباسات عربية - تصميم أنيق بحروف عربية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mouawidate islamique watercolor beige rosée',
    slug: 'mouawidate-watercolor-beige',
    price: 4600,
    images: '[]',
    description: 'المعوذات الإسلامية بالألوان المائية البيج والوردي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique vert',
    slug: 'islamique-vert',
    price: 4600,
    images: '[]',
    description: 'لوحة إسلامية خضراء - تصميم بألوان الطبيعة.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-008',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique doré fond marbré',
    slug: 'islamique-dore-marbre',
    price: 3900,
    images: '[]',
    description: 'لوحة إسلامية ذهبية على خلفية رخامية - تصميم فاخر.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-009',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique Bordeaux & Beige',
    slug: 'islamique-bordeaux-beige',
    price: 1000,
    images: '[]',
    description: 'لوحة إسلامية بوردو وبيج - تصميم أنيق وبسيط.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-010',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Porte moresque',
    slug: 'porte-moresque',
    price: 1400,
    images: '[]',
    description: 'لوحة باب موريسكي - تصاميم العمارة الإسلامية الأندلسية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-011',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'آية الكرسي',
    slug: 'ayat-al-kursi',
    price: 1400,
    images: '[]',
    description: 'آية الكرسي - لوحة إسلامية مباركة.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-012',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique Watercolor Beige',
    slug: 'islamique-watercolor-beige',
    price: 3900,
    images: '[]',
    description: 'لوحة إسلامية بالألوان المائية البيج - تصميم ناعم.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-013',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Modèle islamique',
    slug: 'modele-islamique',
    price: 2600,
    images: '[]',
    description: 'موديل إسلامي - تصميم تقليدي جميل.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-014',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Blue islamique watercolor',
    slug: 'blue-islamique-watercolor',
    price: 3900,
    images: '[]',
    description: 'لوحة إسلامية زرقاء بالألوان المائية - تصميم راقي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-015',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mosque Flower Ayet el kourssi',
    slug: 'mosque-flower-ayat',
    price: 3900,
    images: '[]',
    description: 'مسجد وزهرة مع آية الكرسي - تصميم إسلامي زهري.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-016',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Tassbih poussière marron',
    slug: 'tassbih-poussiere-marron',
    price: 3900,
    images: '[]',
    description: 'تسبيح بدرجات البني - تصميم إسلامي هادئ.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-017',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Al Ryadh وسط الدار',
    slug: 'al-ryadh-wassat-dar',
    price: 2000,
    images: '[]',
    description: 'الرياض وسط الدار - لوحة إسلامية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-018',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mosquée وسط الجامع',
    slug: 'mosquee-wassat-jamie',
    price: 2000,
    images: '[]',
    description: 'مسجد وسط الجامع - لوحة إسلامية جميلة.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-019',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'AYET EL KOURSSI',
    slug: 'ayet-el-kourssi-2',
    price: 2000,
    images: '[]',
    description: 'آية الكرسي - تصميم إسلامي راقي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-020',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Calligraphie Islamique',
    slug: 'calligraphie-islamique',
    price: 2500,
    images: '[]',
    description: 'لوحة خط إسلامي - فن الخط العربي الأصيل.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-021',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'أسماء الله الحسنى',
    slug: 'asmaa-allah-el-hossna',
    price: 2500,
    images: '[]',
    description: 'أسماء الله الحسنى - لوحة إسلامية مباركة.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-022',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 1 floral beige',
    slug: 'ayat-korssi-1-floral-beige',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 1 - تصميم زهري بيج.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-023',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 2 ronde beige abstrait',
    slug: 'ayat-korssi-2-ronde-beige',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 2 - تصميم دائري بيج تجريدي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-024',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 3 plante minimaliste',
    slug: 'ayat-korssi-3-plante',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 3 - تصميم نباتي بسيط.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-025',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 4 noir et blanc',
    slug: 'ayat-korssi-4-noir-blanc',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 4 - تصميم أبيض وأسود.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-026',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 5 watercolor beige',
    slug: 'ayat-korssi-5-watercolor',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 5 - ألوان مائية بيج.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-027',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 6 marbré beige marron',
    slug: 'ayat-korssi-6-marbre',
    price: 2000,
    images: '[]',
    description: 'آية الكرسي 6 - رخام بيج وبني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-028',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 7 géométrique rose',
    slug: 'ayat-korssi-7-geometrique',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 7 - تصميم هندسي وردي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-029',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 9 bois de rose',
    slug: 'ayat-korssi-9-bois-rose',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 9 - بخشب الورد.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-030',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 10 floral rose & gris',
    slug: 'ayat-korssi-10-rose-gris',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 10 - زهري ورمادي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-031',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 11 rose & violet',
    slug: 'ayat-korssi-11-rose-violet',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 11 - وردي وبنفسجي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-032',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 12 marron',
    slug: 'ayat-korssi-12-marron',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 12 - تصميم بني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-033',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 13 beige marron',
    slug: 'ayat-korssi-13-beige-marron',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 13 - بيج وبني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-034',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi grise',
    slug: 'ayat-korssi-grise',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي رمادية - تصميم أنيق.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-035',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 15 beige rosée',
    slug: 'ayat-korssi-15-beige-rose',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 15 - بيج وردي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-036',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 16 dorée',
    slug: 'ayat-korssi-16-doree',
    price: 1600,
    images: '[]',
    description: 'آية الكرسي 16 - تصميم ذهبي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-037',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mouawidat 17 marbré rose gris',
    slug: 'mouawidat-17-marbre',
    price: 2000,
    images: '[]',
    description: 'المعوذات 17 - رخام وردي ورمادي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-038',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el kourssi 21 beige floral',
    slug: 'ayat-kourssi-21-floral',
    price: 2500,
    images: '[]',
    description: 'آية الكرسي 21 - بيج زهري.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-039',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 22 poussière marron',
    slug: 'ayat-korssi-22-poussiere',
    price: 2500,
    images: '[]',
    description: 'آية الكرسي 22 - ترابي بني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-040',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 23 floral doré',
    slug: 'ayat-korssi-23-floral-dore',
    price: 2500,
    images: '[]',
    description: 'آية الكرسي 23 - زهري ذهبي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-041',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Ayet el korssi 24 marbré marron',
    slug: 'ayat-korssi-24-marbre-marron',
    price: 2500,
    images: '[]',
    description: 'آية الكرسي 24 - رخام بني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-042',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Bissmillah beige feuille d\'or',
    slug: 'bissmillah-beige-feuille-or',
    price: 2500,
    images: '[]',
    description: 'بسم الله - بيج مع أوراق ذهبية. تصميم فاخر.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-043',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Islamique marron',
    slug: 'islamique-marron-2',
    price: 3200,
    images: '[]',
    description: 'لوحة إسلامية بنية - تصميم دافئ.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-044',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Porte Moresque 1',
    slug: 'porte-moresque-1',
    price: 2000,
    images: '[]',
    description: 'باب موريسكي 1 - فن العمارة الأندلسية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-045',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Porte Moresque 2',
    slug: 'porte-moresque-2',
    price: 1600,
    images: '[]',
    description: 'باب موريسكي 2 - فن العمارة الأندلسية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-046',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Sabr Houb Shukr Beige',
    slug: 'sabr-houb-shukr-beige-isl',
    price: 4600,
    images: '[]',
    description: 'صبر حب شكر بيج - كلمات إسلامية جميلة.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-047',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'El Riadh Vert',
    slug: 'el-riadh-vert',
    price: 1600,
    images: '[]',
    description: 'الرياض أخضر - تصميم إسلامي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-048',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Home Doua دعاء البيت',
    slug: 'home-doua',
    price: 950,
    images: '[]',
    description: 'دعاء البيت - لوحة إسلامية للبركة في المنزل.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-049',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'دعاء رمضان',
    slug: 'doua-ramadan',
    price: 950,
    images: '[]',
    description: 'دعاء رمضان - لوحة إسلامية شهر رمضان.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-050',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'دعاء الصيام',
    slug: 'doua-siyam',
    price: 950,
    images: '[]',
    description: 'دعاء الصيام - لوحة إسلامية.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-051',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Architecture Islamique Arabesque Porte Beige',
    slug: 'architecture-islamique-porte-beige',
    price: 4600,
    images: '[]',
    description: 'عمارة إسلامية - باب عربي بيج. فن معماري أندلسي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-052',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pack Islamique watercolor beige rosée',
    slug: 'pack-islamique-watercolor',
    price: 4000,
    images: '[]',
    description: 'باقة إسلامية بالألوان المائية البيج والوردي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-053',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Sabr • Shukr • Tawakkul Floral',
    slug: 'sabr-shukr-tawakkul-floral',
    price: 3900,
    images: '[]',
    description: 'صبر • شكر • توكل - تصميم زهري إسلامي.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-054',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'أسماء الله الحسنى marbré beige marron',
    slug: 'asmaa-allah-marbre-beige',
    price: 2000,
    images: '[]',
    description: 'أسماء الله الحسنى - رخام بيج بني.',
    color: '#a10510',
    category: cat('islamique'),
    sku: 'ORVA-ISL-055',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // MÉDICAL
  {
    name: 'Laboratoire en couleur',
    slug: 'laboratoire-couleur',
    price: 4600,
    images: '[]',
    description: 'لوحة مختبر ملونة - ديكور جميل للعيادات والمختبرات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Laboratoire Bleu Moutarde',
    slug: 'laboratoire-bleu-moutarde',
    price: 4600,
    images: '[]',
    description: 'لوحة مختبر أزرق وخردلي - تصميم أنيق للمختبرات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cabinet médicale coloré',
    slug: 'cabinet-medical-colore',
    price: 4600,
    images: '[]',
    description: 'لوحة عيادة طبية ملونة - ديكور للعيادات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Médicale Floral',
    slug: 'medicale-floral',
    price: 4000,
    images: '[]',
    description: 'لوحة طبية زهرية - مزيج من الطب والطبيعة.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Psychologie médecin-patient',
    slug: 'psychologie-medecin-patient',
    price: 2800,
    images: '[]',
    description: 'لوحة علم النفس - طبيب ومريض. ديكور لعيادة النفسية.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Psychologie Colorée',
    slug: 'psychologie-coloree',
    price: 2800,
    images: '[]',
    description: 'لوحة علم النفس ملونة - تصميم مرح وحديث.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Psychologie 3 Féminin',
    slug: 'psychologie-3-feminin',
    price: 3900,
    images: '[]',
    description: 'لوحة علم النفس 3 - تصميم أنثوي.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dentiste Floral (6 tailles similaires)',
    slug: 'dentiste-floral-6-similaire',
    price: 4800,
    images: '[]',
    description: 'لوحة أسنان زهرية - 6 قطع بنفس الحجم.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-008',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dentiste Floral (6 tailles différentes)',
    slug: 'dentiste-floral-6-differentes',
    price: 5400,
    images: '[]',
    description: 'لوحة أسنان زهرية - 6 قطع بأحجام مختلفة.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-009',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Médecin Généraliste',
    slug: 'medecin-generaliste',
    price: 3900,
    images: '[]',
    description: 'لوحة طبيب عام - ديكور عيادة الطب العام.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-010',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Coeur colorée',
    slug: 'coeur-colore',
    price: 1400,
    images: '[]',
    description: 'لوحة قلب ملون - ديكور جميل للعيادة.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-011',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cerveau colorée',
    slug: 'cerveau-colore',
    price: 1400,
    images: '[]',
    description: 'لوحة دماغ ملون - ديكور لعيادة الأعصاب.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-012',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Gynécologie floral',
    slug: 'gynecologie-floral',
    price: 3900,
    images: '[]',
    description: 'لوحة نسائية زهرية - ديكور لعيادة النساء.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-013',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Psychologie floral',
    slug: 'psychologie-floral',
    price: 3900,
    images: '[]',
    description: 'لوحة علم النفس زهرية - تصميم ناعم.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-014',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait Ophtalmo Noir',
    slug: 'abstrait-ophtalmo-noir',
    price: 3000,
    images: '[]',
    description: 'لوحة عيون تجريدية سوداء - ديكور لعيادة العيون.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-015',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pregnant woman flowers',
    slug: 'pregnant-woman-flowers',
    price: 2500,
    images: '[]',
    description: 'لوحة امرأة حامل مع زهور - تصميم جميل.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-016',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mère & enfant',
    slug: 'mere-et-enfant',
    price: 2500,
    images: '[]',
    description: 'لوحة أم وطفل - تصميم دافئ.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-017',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Instruments dentaire',
    slug: 'instruments-dentaire',
    price: 2000,
    images: '[]',
    description: 'لوحة أدوات أسنان - ديكور لعيادة الأسنان.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-018',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Laboratoire 1',
    slug: 'laboratoire-1',
    price: 2000,
    images: '[]',
    description: 'لوحة مختبر 1 - ديكور للمختبرات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-019',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Laboratoire 2',
    slug: 'laboratoire-2',
    price: 2000,
    images: '[]',
    description: 'لوحة مختبر 2 - ديكور للمختبرات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-020',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Cerveau colorée 2',
    slug: 'cerveau-colore-2',
    price: 2000,
    images: '[]',
    description: 'لوحة دماغ ملون 2 - ديكور عصبي.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-021',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Poumon floral',
    slug: 'poumon-floral',
    price: 2000,
    images: '[]',
    description: 'لوحة رئة زهرية - ديكور لطب الرئة.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-022',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstract eye',
    slug: 'abstract-eye',
    price: 2000,
    images: '[]',
    description: 'لوحة عين تجريدية - ديكور لعيادة العيون.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-023',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstract Eye 2',
    slug: 'abstract-eye-2',
    price: 2500,
    images: '[]',
    description: 'لوحة عين تجريدية 2 - ديكور لعيادة العيون.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-024',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Appareil Dentaire',
    slug: 'appareil-dentaire',
    price: 2000,
    images: '[]',
    description: 'لوحة جهاز أسنان - ديكور عيادة تقويم الأسنان.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-025',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Médicale microscope',
    slug: 'medicale-microscope',
    price: 3000,
    images: '[]',
    description: 'لوحة مجهر طبي - ديكور للمختبرات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-026',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dents fleuries',
    slug: 'dents-fleuries',
    price: 1600,
    images: '[]',
    description: 'لوحة أسنان مزهرة - تصميم جميل لعيادة الأسنان.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-027',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Trio Gynécologie',
    slug: 'trio-gynecologie',
    price: 4600,
    images: '[]',
    description: 'لوحة ثلاثية نسائية - ديكور لعيادة النساء.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-028',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dentiste Bleu Moutarde',
    slug: 'dentiste-bleu-moutarde',
    price: 2400,
    images: '[]',
    description: 'لوحة أسنان أزرق وخردلي - تصميم أنيق.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-029',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Henri Matisse Joy of Smiles médical',
    slug: 'henri-matisse-joy-medical',
    price: 2500,
    images: '[]',
    description: 'لوحة هنري ماتيس - فرحة الابتسامات للعيادات.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-030',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dental Line Art',
    slug: 'dental-line-art',
    price: 3900,
    images: '[]',
    description: 'لوحة خطوط أسنان - تصميم فني لعيادة الأسنان.',
    color: '#a10510',
    category: cat('medical'),
    sku: 'ORVA-MED-031',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // PAYSAGE / FLORAL
  {
    name: 'Doua floral ولسوف يعطيك ربك فترضى rose',
    slug: 'doua-yardha-rose-paysage',
    price: 2500,
    images: '[]',
    description: 'دعاء فلورال - ولسوف يعطيك ربك فترضى. تصميم وردي.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Floral fushia vert',
    slug: 'floral-fushia-vert',
    price: 4600,
    images: '[]',
    description: 'لوحة زهور فوشيا وخضراء - ألوان زاهية وجريئة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pink Flowers',
    slug: 'pink-flowers',
    price: 4600,
    images: '[]',
    description: 'لوحة زهور وردية - تصميم زهري جميل.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Flower Beige aesthetic',
    slug: 'flower-beige-aesthetic',
    price: 4600,
    images: '[]',
    description: 'لوحة زهور بيج aesthetic - تصميم أنيق وعصري.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Plante Bleu',
    slug: 'plante-bleu',
    price: 4600,
    images: '[]',
    description: 'لوحة نباتات زرقاء - لمسة طبيعية زرقاء.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Dream Hope Plume Beige',
    slug: 'dream-hope-plume-beige',
    price: 4600,
    images: '[]',
    description: 'حلم أمل ريشة بيج - تصميم ملهم وناعم.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Feuilles Noir',
    slug: 'feuilles-noir',
    price: 4600,
    images: '[]',
    description: 'لوحة أوراق سوداء - تصميم جريء وأنيق.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Summer vibes',
    slug: 'summer-vibes',
    price: 4800,
    oldPrice: 5400,
    images: '[]',
    description: 'أجواء الصيف - لوحة مشرقة ومليئة بالحيوية.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-008',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs bleu ciel et blanc',
    slug: 'fleurs-bleu-ciel-blanc',
    price: 2000,
    images: '[]',
    description: 'لوحة زهور أزرق سماوي وأبيض - تصميم منعش.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-009',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Plume gold',
    slug: 'plume-gold',
    price: 3900,
    images: '[]',
    description: 'لوحة ريشة ذهبية - تصميم فاخر.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-010',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pampas beige',
    slug: 'pampas-beige',
    price: 3900,
    images: '[]',
    description: 'لوحة بامباس بيج - تصميم ناعم وعصري.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-011',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pampas botanique vert',
    slug: 'pampas-botanique-vert',
    price: 4800,
    images: '[]',
    description: 'لوحة بامباس نباتية خضراء - تصميم طبيعي.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-012',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 1',
    slug: 'paysage-1',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 1 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-013',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 2',
    slug: 'paysage-2',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 2 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-014',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 3',
    slug: 'paysage-3',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 3 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-015',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 4',
    slug: 'paysage-4',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 4 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-016',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 5',
    slug: 'paysage-5',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 5 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-017',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 6',
    slug: 'paysage-6',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 6 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-018',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 7',
    slug: 'paysage-7',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 7 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-019',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 8',
    slug: 'paysage-8',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 8 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-020',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 9',
    slug: 'paysage-9',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 9 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-021',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 10',
    slug: 'paysage-10',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 10 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-022',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Paysage 11',
    slug: 'paysage-11',
    price: 2500,
    images: '[]',
    description: 'منظر طبيعي 11 - لوحة مناظر طبيعية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-023',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Couleur automnales bleu-gris & rouge brique',
    slug: 'couleurs-automnales',
    price: 2000,
    images: '[]',
    description: 'ألوان خريفية أزرق-رمادي وأحمر طوب.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-024',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Florale Beige',
    slug: 'florale-beige',
    price: 2000,
    images: '[]',
    description: 'لوحة زهور بيج - تصميم ناعم.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-025',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Floral Bleu',
    slug: 'floral-bleu',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور زرقاء - تصميم زهري.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-026',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs Bleu-Gris',
    slug: 'fleurs-bleu-gris',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور أزرق-رمادي.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-027',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleur Bleu nuit',
    slug: 'fleur-bleu-nuit',
    price: 3000,
    images: '[]',
    description: 'لوحة زهرة زرقاء ليلية.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-028',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs Blanche et Bleutées',
    slug: 'fleurs-blanche-bleutees',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور بيضاء ومائلة للزرقة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-029',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait Florales Bleu',
    slug: 'abstrait-florales-bleu',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور تجريدية زرقاء.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-030',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait fleurs bleu intense avec doré',
    slug: 'abstrait-fleurs-bleu-intense-dore',
    price: 3000,
    images: '[]',
    description: 'لوحة تجريدية زهور زرقاء مع ذهبي.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-031',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Fleurs et couleurs',
    slug: 'fleurs-et-couleurs',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور وألوان.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-032',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Floral violet et bleu',
    slug: 'floral-violet-bleu',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور بنفسجية وزرقاء.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-033',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Nature vague noir',
    slug: 'nature-vague-noir',
    price: 3000,
    images: '[]',
    description: 'طبيعة موجات سوداء - تصميم عصري.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-034',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Floral abstrait rose',
    slug: 'floral-abstrait-rose',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور تجريدية وردية.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-035',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Creativa Déco Feuilles d\'Élégance Verte',
    slug: 'feuilles-elegance-verte',
    price: 3200,
    images: '[]',
    description: 'أوراق الأناقة الخضراء - تصميم طبيعي.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-036',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Palm & Beach (Summer Plage)',
    slug: 'palm-beach-summer',
    price: 8400,
    images: '[]',
    description: 'نخيل وشاطئ - أجواء الصيف على الشاطئ.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-037',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Summer Vibes 2',
    slug: 'summer-vibes-2',
    price: 7000,
    images: '[]',
    description: 'أجواء الصيف 2 - لوحة صيفية جميلة.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-038',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Neutral Tone 1 Beige',
    slug: 'neutral-tone-1-beige',
    price: 3200,
    images: '[]',
    description: 'نغمات محايدة 1 بيج - تصميم هادئ.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-039',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Neutral Tone 2 Beige',
    slug: 'neutral-tone-2-beige',
    price: 3200,
    images: '[]',
    description: 'نغمات محايدة 2 بيج - تصميم هادئ.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-040',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Plage calme',
    slug: 'plage-calme',
    price: 3000,
    images: '[]',
    description: 'شاطئ هادئ - لوحة مناظر شاطئية.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-041',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Floral rose long',
    slug: 'floral-rose-long',
    price: 3800,
    images: '[]',
    description: 'لوحة زهور وردية طويلة - تصميم عمودي أنيق.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-042',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Feuille rose doré long',
    slug: 'feuille-rose-dore-long',
    price: 3800,
    images: '[]',
    description: 'ورقة وردية ذهبية طويلة - تصميم عمودي فاخر.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-043',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait floral 42',
    slug: 'abstrait-floral-42',
    price: 3000,
    images: '[]',
    description: 'لوحة زهور تجريدية 42.',
    color: '#a10510',
    category: cat('paysage'),
    sku: 'ORVA-PAY-044',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // PACK DE 6
  {
    name: 'Pack de 6 Plume et Pampas',
    slug: 'pack-6-plume-pampas',
    price: 5000,
    images: '[]',
    description: 'باقة 6 لوحات - ريشة وبامباس. مجموعة متناسقة.',
    color: '#a10510',
    category: cat('pack6'),
    sku: 'ORVA-P6-001',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pack de 6 Nude',
    slug: 'pack-6-nude',
    price: 4800,
    oldPrice: 5400,
    images: '[]',
    description: 'باقة 6 لوحات nude - ألوان محايدة وأنيقة.',
    color: '#a10510',
    category: cat('pack6'),
    sku: 'ORVA-P6-002',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pack de 6 Summer vibes',
    slug: 'pack-6-summer-vibes',
    price: 4800,
    oldPrice: 5400,
    images: '[]',
    description: 'باقة 6 لوحات - أجواء الصيف.',
    color: '#a10510',
    category: cat('pack6'),
    sku: 'ORVA-P6-003',
    stock: 5,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Pack de 6 Orange Beige',
    slug: 'pack-6-orange-beige',
    price: 5000,
    oldPrice: 5600,
    images: '[]',
    description: 'باقة 6 لوحات - برتقالي وبيج.',
    color: '#a10510',
    category: cat('pack6'),
    sku: 'ORVA-P6-004',
    stock: 5,
    active: true,
    position: nextPos(),
  },

  // DUO
  {
    name: 'Duo black & beige',
    slug: 'duo-black-beige',
    price: 4000,
    images: '[]',
    description: 'لوحة ثنائية أسود وبيج.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-001',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Duo Horizon Bleu',
    slug: 'duo-horizon-bleu',
    price: 3200,
    images: '[]',
    description: 'لوحة ثنائية أفق أزرق.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-002',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Duo Beige & Noir',
    slug: 'duo-beige-noir',
    price: 6400,
    images: '[]',
    description: 'لوحة ثنائية بيج وأسود.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-003',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait Wavy Verde',
    slug: 'abstrait-wavy-verde',
    price: 3200,
    images: '[]',
    description: 'لوحة تجريدية متموجة خضراء.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-004',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Duo Abstrait nuance Bleu, gris, beige',
    slug: 'duo-abstrait-bleu-gris-beige',
    price: 4000,
    images: '[]',
    description: 'لوحة ثنائية تجريدية أزرق رمادي بيج.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-005',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Lueur Marine Bleu',
    slug: 'lueur-marine-bleu',
    price: 4000,
    images: '[]',
    description: 'وهج بحري أزرق - لوحة ثنائية.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-006',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Mouvement Abstrait Nuance Bois de Rose',
    slug: 'mouvement-abstrait-bois-rose',
    price: 4000,
    images: '[]',
    description: 'حركة تجريدية بخشب الورد.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-007',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Contemporain Bleu',
    slug: 'contemporain-bleu',
    price: 3200,
    images: '[]',
    description: 'لوحة معاصرة زرقاء.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-008',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Abstrait Neutre Line Noir',
    slug: 'abstrait-neutre-line-noir',
    price: 3200,
    images: '[]',
    description: 'لوحة تجريدية محايدة بخطوط سوداء.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-009',
    stock: 10,
    active: true,
    position: nextPos(),
  },
  {
    name: 'Équilibre Beige & Noir gris',
    slug: 'equilibre-beige-noir-gris',
    price: 3200,
    images: '[]',
    description: 'توازن بيج وأسود رمادي.',
    color: '#a10510',
    category: cat('duo'),
    sku: 'ORVA-DUO-010',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  // Keep existing orva products
  {
    name: 'هدية خريطة الزفاف المؤطرة - إطار زواج مخصص مع الموقع والتاريخ',
    slug: 'framed-wedding-map-gift',
    price: 2900,
    images: JSON.stringify([
      'https://i.etsystatic.com/25506271/r/il/f07fa1/5359325661/il_fullxfull.5359325661_syah.jpg',
      'https://i.etsystatic.com/25506271/r/il/1f160f/6748245514/il_fullxfull.6748245514_kwkc.jpg',
      'https://i.etsystatic.com/25506271/r/il/3c589a/6748246404/il_fullxfull.6748246404_8opc.jpg',
      'https://i.etsystatic.com/25506271/r/il/dd60aa/6620833390/il_fullxfull.6620833390_bhgu.jpg',
      'https://i.etsystatic.com/25506271/r/il/d84215/6417522117/il_fullxfull.6417522117_e43d.jpg',
    ]),
    description: 'هدية زفاف مخصصة وجميلة للعروسين.\nتتميز الإطارة بأسماء العروسين، الموقع الدقيق للزواج مع قلب، والتاريخ على التقويم.\n\nمؤطرة بالكامل في إطار صندوقي بزجاج أمامي.\nتأتي مع صندوق تقديم خاص بها جاهزة للتغليف والإهداء.\n\n• إطار زجاجي أمامي\n• تصميم مخصص حسب الطلب\n• هدية مثالية للعرسان\n• تأتي مع صندوق هدايا',
    color: '#a10510',
    category: 'orva',
    sku: 'ORVA-WEDMAP',
    stock: 10,
    active: true,
    position: nextPos(),
  },

  {
    name: 'إطار كانفاس على شاسيه 55x70 سم - أسماء العروسين وتاريخ الزفاف',
    slug: 'canvas-frame-55x70-wedding-names-date',
    price: 3400,
    images: JSON.stringify([]),
    description: 'إطار كانفاس (توال) على شاسيه خشبي مقاس 55×70 سم.\n\nمطبوع بأسماء العروسين وتاريخ الزفاف.\n\n• قماش كانفاس عالي الجودة\n• شاسيه خشبي متين\n• مقاس 55×70 سم\n• طباعة بأسماء العروسين وتاريخ الزفاف\n• جاهز للتعليق\n• هدية زفاف مثالية',
    color: '#a10510',
    category: 'orva',
    sku: 'ORVA-CNV55',
    stock: 15,
    active: true,
    position: nextPos(),
  },
];

async function main() {
  const count = await prisma.product.count();
  if (count > 0) {
    console.log(`⚠️ Database already has ${count} products — deleting all and re-seeding`);
    await prisma.orderItem.deleteMany();
    await prisma.review.deleteMany();
    await prisma.product.deleteMany();
    console.log('🗑️ Deleted all existing products');
  }

  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
    console.log(`✅ ${p.name}`);
  }
  console.log(`\n🎉 Seeded ${products.length} product(s) total`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
